//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionRowResultChild
    {
        public int ChildResultID { get; set; }
        public int ActionRowID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public Nullable<System.DateTime> RDate { get; set; }
        public string Description { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
