//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionRowProcess
    {
        public int ID { get; set; }
        public int ActionID { get; set; }
        public int ActionRowID { get; set; }
        public System.DateTime Date { get; set; }
        public int Year { get; set; }
        public int Week { get; set; }
        public int TypeID { get; set; }
        public Nullable<double> TotalIN { get; set; }
        public Nullable<double> TotalOUT { get; set; }
        public string Money { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
