//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionRow
    {
        public int ID { get; set; }
        public int ActionID { get; set; }
        public Nullable<System.Guid> ActionRowUID { get; set; }
        public int StateID { get; set; }
        public System.DateTime Date { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> Day { get; set; }
        public string DateWMonth { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual ResultState ResultState { get; set; }
    }
}
