//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionAccounts
    {
        public int AccountID { get; set; }
        public string SourceName { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> TotalDebit { get; set; }
        public Nullable<double> TotalCredit { get; set; }
        public string Money { get; set; }
        public string Description { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
