//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Action()
        {
            this.ActionRow = new HashSet<ActionRow>();
        }
    
        public int ActionID { get; set; }
        public System.Guid ActionUID { get; set; }
        public int StateID { get; set; }
        public System.DateTime ActionDate { get; set; }
        public int LocationID { get; set; }
        public Nullable<double> Metarials { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Week { get; set; }
    
        public virtual ResultState ResultState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionRow> ActionRow { get; set; }
    }
}
