//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionRowExpense
    {
        public int ID { get; set; }
        public int ActionID { get; set; }
        public Nullable<int> ActionRowID { get; set; }
        public int LocationID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string MaterialName { get; set; }
        public string Unitdesc { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate1 { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
