//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionRowResult
    {
        public int ResultID { get; set; }
        public int ActionID { get; set; }
        public int ActionRowID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public System.DateTime ResultDate { get; set; }
        public int StateID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> SubStatusID { get; set; }
        public string Description { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> CashIN { get; set; }
        public Nullable<double> LaborPayed { get; set; }
        public Nullable<double> LaborPayedPayed { get; set; }
        public Nullable<double> Expense { get; set; }
        public Nullable<System.DateTime> ZTime { get; set; }
        public string ZNumber { get; set; }
        public Nullable<double> ZNetTotal { get; set; }
        public Nullable<double> ZGeneralTotal { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> IsSendPackage { get; set; }
        public Nullable<bool> IsReceivePackage { get; set; }
        public string EnvelopeFile { get; set; }
        public Nullable<bool> IsMaster { get; set; }
        public Nullable<bool> NotOpened { get; set; }
        public string AdminDescription { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ResultState ResultState { get; set; }
    }
}
