//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int ID { get; set; }
        public int ChassisID { get; set; }
        public int CostumeID { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> ConstractDate { get; set; }
        public string Photo { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
