//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationLog
    {
        public long ID { get; set; }
        public string Environment { get; set; }
        public string Modul { get; set; }
        public string ProcessType { get; set; }
        public string ProcessID { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string Data { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string ResultMessage { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string RecordEmployee { get; set; }
        public string RecordIP { get; set; }
        public string RecordDevice { get; set; }
    }
}
