//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankNotification
    {
        public long ID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> BankAccountID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public string DocumentNumber { get; set; }
        public string ReferenceCode { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<double> Commission { get; set; }
        public Nullable<double> NetTotal { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public string TransactionID { get; set; }
        public string ReceiptFile { get; set; }
        public Nullable<bool> IsReceipt { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> RecordEmployee { get; set; }
        public string RecordIP { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
