//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardReaderParameter
    {
        public long ID { get; set; }
        public Nullable<int> CardReaderID { get; set; }
        public string SerialNumber { get; set; }
        public string MACAddress { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Version { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> MiliSecond { get; set; }
        public Nullable<int> ReadCount { get; set; }
        public Nullable<int> UnitDuration { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    }
}
