//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardType
    {
        public short ID { get; set; }
        public string CardTypeName { get; set; }
        public Nullable<bool> AllowLoading { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<bool> IsInventory { get; set; }
        public Nullable<bool> IsZeroStock { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
