//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardActionsHistory
    {
        public long ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<long> CardID { get; set; }
        public string CardNumber { get; set; }
        public Nullable<int> CardReaderID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<long> SaleID { get; set; }
        public Nullable<long> SaleRowID { get; set; }
        public Nullable<long> ProcessID { get; set; }
        public Nullable<System.Guid> ProcessUID { get; set; }
        public Nullable<short> ActionTypeID { get; set; }
        public string ActionTypeName { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<double> CreditCharge { get; set; }
        public Nullable<double> CreditSpend { get; set; }
        public double Credit { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> IsPromotion { get; set; }
        public Nullable<System.DateTime> ActionDateUpdate { get; set; }
        public Nullable<short> CardTypeID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    }
}
