//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardReader
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> LocationTypeID { get; set; }
        public Nullable<int> LocationPartID { get; set; }
        public string PartName { get; set; }
        public string PartGroupName { get; set; }
        public string SerialNumber { get; set; }
        public string MACAddress { get; set; }
        public Nullable<int> CardReaderTypeID { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Version { get; set; }
        public string IPAddress { get; set; }
    }
}
