//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardReaderAction
    {
        public long ID { get; set; }
        public Nullable<int> CardReaderID { get; set; }
        public Nullable<System.Guid> CardReaderUID { get; set; }
        public string SerialNumber { get; set; }
        public string MACAddress { get; set; }
        public Nullable<short> ProcessType { get; set; }
        public Nullable<short> ProcessNumber { get; set; }
        public Nullable<short> CardType { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<double> RideAmount { get; set; }
        public Nullable<double> CardBalanceAmount { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    }
}
