//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash
    {
        public int ID { get; set; }
        public int LocationID { get; set; }
        public string CashName { get; set; }
        public Nullable<double> BlockedAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> IsMaster { get; set; }
        public string SortBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
