//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCard
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CardStatus { get; set; }
        public string CardNumber { get; set; }
        public Nullable<bool> IsMaster { get; set; }
        public Nullable<System.DateTime> DateRecord { get; set; }
        public Nullable<System.Guid> Token { get; set; }
        public Nullable<System.DateTime> TokenExpire { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
