//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerScorePointRules
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> FromScoreItemID { get; set; }
        public Nullable<int> ToScroreItemID { get; set; }
        public Nullable<double> QuantityFrom { get; set; }
        public Nullable<double> QuantityTo { get; set; }
        public Nullable<System.DateTime> DateRecord { get; set; }
    }
}
