//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTansactions
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string MerchandName { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionNumber { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Commission { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string Currency { get; set; }
        public string CardPan { get; set; }
        public string HolderName { get; set; }
        public string ExpDate { get; set; }
        public string CCV2 { get; set; }
        public string ResultMessage { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public Nullable<int> CustomerCardID { get; set; }
    }
}
