//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerScorePointRules
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<int> QuantityPoint { get; set; }
        public Nullable<int> QuantityTicket { get; set; }
    }
}
