//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateList
    {
        public int DateID { get; set; }
        public System.DateTime DateKey { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> DayOfYear { get; set; }
        public string MonthName { get; set; }
        public string DayName { get; set; }
        public string MonthNameTR { get; set; }
        public string DayNameTR { get; set; }
        public Nullable<int> Quarter { get; set; }
        public string Description { get; set; }
        public Nullable<int> WeekYear { get; set; }
        public Nullable<int> WeekNumber { get; set; }
    }
}
