//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayResultItemList
    {
        public long ID { get; set; }
        public Nullable<long> ResultID { get; set; }
        public string Category { get; set; }
        public Nullable<int> ResultItemID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> SystemAmount { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<double> UnitHourPrice { get; set; }
        public Nullable<double> HourQuantity { get; set; }
        public Nullable<double> SystemHourQuantity { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
    
        public virtual DayResult DayResult { get; set; }
        public virtual DayResultItems DayResultItems { get; set; }
    }
}
