//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentPartnerEarn
    {
        public long ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public string PeriodCode { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> FromBankAccountID { get; set; }
        public Nullable<int> PartnerID { get; set; }
        public Nullable<double> PartnerRate { get; set; }
        public Nullable<double> CapacityRate { get; set; }
        public Nullable<double> GrossAmount { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> PartnerActionTypeID { get; set; }
        public string ActionTypeName { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<double> SystemAmount { get; set; }
        public string SystemCurrency { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public string RecordIP { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployee { get; set; }
        public string UpdateIP { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public Nullable<bool> IsAutoCompute { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<double> AmountEarned { get; set; }
    }
}
