//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSalaryEarn
    {
        public long ID { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> QuantityHour { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public string RecordIP { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployee { get; set; }
        public string UpdateIP { get; set; }
        public Nullable<long> ReferenceID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ActionTypeName { get; set; }
        public Nullable<int> ActionTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<long> ResultID { get; set; }
        public Nullable<int> EnvironmentID { get; set; }
        public Nullable<System.Guid> UID { get; set; }
    }
}
