//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCashActions
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ActionTypeID { get; set; }
        public string ProcessName { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string ProcessDetail { get; set; }
        public Nullable<double> CashEarned { get; set; }
        public Nullable<double> CashPaid { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
