//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDismissal
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> StageID { get; set; }
        public Nullable<System.DateTime> DateKey { get; set; }
        public string DismissalRule { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> RecordDateDate { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
