//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeeLocation = new HashSet<EmployeeLocation>();
        }
    
        public int EmployeeID { get; set; }
        public string IdentityNumber { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public string FullNameSearch { get; set; }
        public string EMail { get; set; }
        public string Mobile { get; set; }
        public string SmsNumber { get; set; }
        public string Mobile2 { get; set; }
        public string Whatsapp { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FotoFile { get; set; }
        public Nullable<int> RoleID { get; set; }
        public int OurCompanyID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsTemp { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDismissal { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string DismissDescription { get; set; }
        public Nullable<System.Guid> EmployeeUID { get; set; }
        public Nullable<int> ShiftTypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> RoleGroupID { get; set; }
        public string RecordIP { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateIP { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> AreaCategoryID { get; set; }
        public Nullable<int> SalaryCategoryID { get; set; }
        public Nullable<int> SequenceID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string IdentityType { get; set; }
        public string CountryPhoneCode { get; set; }
        public string Address { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> City { get; set; }
        public string PostCode { get; set; }
        public string IBAN { get; set; }
        public Nullable<int> BankID { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual RoleGroup RoleGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLocation> EmployeeLocation { get; set; }
        public virtual OurCompany OurCompany { get; set; }
    }
}
