//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePeriods
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractFinishDate { get; set; }
        public System.DateTime FinalFinishDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> RecordedEmployeeID { get; set; }
        public string RecordIP { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public string UpdateIP { get; set; }
        public Nullable<int> EmployeeStatusID { get; set; }
        public Nullable<int> ShiftTypeID { get; set; }
        public Nullable<int> RoleGroupID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> AreaCategoryID { get; set; }
        public Nullable<int> SalaryCategoryID { get; set; }
        public Nullable<int> SequenceID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
