//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseCenter
    {
        public int ID { get; set; }
        public int OurCompanyID { get; set; }
        public string ExpenseCenterName { get; set; }
        public bool ProfitCenter { get; set; }
        public bool ExpenseCenter1 { get; set; }
        public string SortBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
