//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseDucumentChart
    {
        public long ID { get; set; }
        public Nullable<int> ExpenseDucumentID { get; set; }
        public Nullable<short> ExpenseItemID { get; set; }
        public Nullable<double> DistributionAmount { get; set; }
        public Nullable<double> DistributedRate { get; set; }
        public Nullable<double> DistributedAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.Guid> UID { get; set; }
    }
}
