//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    
    public partial class GetLocationEmployees_Result1
    {
        public int EmployeeID { get; set; }
        public Nullable<System.Guid> EmployeeUID { get; set; }
        public string FullName { get; set; }
        public string PositionName { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
