//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityType
    {
        public int ID { get; set; }
        public string TypeCode { get; set; }
        public string TypeName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
