//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionItem
    {
        public int Id { get; set; }
        public Nullable<int> InspectionID { get; set; }
        public Nullable<int> InspectionCatID { get; set; }
        public string Number { get; set; }
        public string ItemName { get; set; }
        public string SortBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
