//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectorReportEmployeeRows
    {
        public int ID { get; set; }
        public Nullable<int> ReportID { get; set; }
        public Nullable<int> ReportEmployeeID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> KeyID { get; set; }
        public Nullable<bool> Result { get; set; }
        public string Description { get; set; }
    }
}
