//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationShift
    {
        public int ID { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> EmployeeIDFinish { get; set; }
        public System.DateTime ShiftDate { get; set; }
        public Nullable<System.TimeSpan> ShiftStart { get; set; }
        public Nullable<System.TimeSpan> ShiftFinish { get; set; }
        public string Duration { get; set; }
        public Nullable<double> LatitudeStart { get; set; }
        public Nullable<double> LongitudeStart { get; set; }
        public Nullable<bool> FromMobileStart { get; set; }
        public Nullable<double> LatitudeFinish { get; set; }
        public Nullable<double> LongitudeFinish { get; set; }
        public Nullable<bool> FromMobileFinish { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> ShiftDateStart { get; set; }
        public Nullable<System.DateTime> ShiftDateFinish { get; set; }
        public Nullable<int> DurationMinute { get; set; }
    }
}
