//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int LocationID { get; set; }
        public string LocationCode { get; set; }
        public Nullable<int> LocationTypeID { get; set; }
        public string LocationName { get; set; }
        public string LocationNameSearch { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> Timezone { get; set; }
        public string MapURL { get; set; }
        public int OurCompanyID { get; set; }
        public string ImageFile { get; set; }
        public Nullable<bool> IsHaveOperator { get; set; }
        public string IP { get; set; }
        public string EnforcedWarning { get; set; }
        public string SortBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Currency { get; set; }
        public Nullable<int> PriceCatID { get; set; }
        public string Weight { get; set; }
        public string Distance { get; set; }
        public Nullable<System.DateTime> LocalDate { get; set; }
        public Nullable<System.DateTime> LocalDateTime { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public string RecordIP { get; set; }
        public Nullable<System.Guid> LocationUID { get; set; }
        public Nullable<int> POSAccountID { get; set; }
        public string LocationFullName { get; set; }
        public Nullable<int> MallID { get; set; }
    }
}
