//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationShiftSet
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> ShiftDate { get; set; }
        public Nullable<System.TimeSpan> ShiftStart { get; set; }
        public Nullable<System.TimeSpan> ShiftFinish { get; set; }
        public string Duration { get; set; }
        public Nullable<bool> DeliberatelyClosed { get; set; }
        public Nullable<bool> OperatorFailedToOpen { get; set; }
    }
}
