//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationCardReaderParameter
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> LocationTypeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public double UnitPrice { get; set; }
        public int MiliSecond { get; set; }
        public int ReadCount { get; set; }
        public int UnitDuration { get; set; }
    }
}
