//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationEmployeeCheck
    {
        public int LocationID { get; set; }
        public string SortBy { get; set; }
        public string LocationName { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
        public int EmployeeID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> Expr1 { get; set; }
    }
}
