//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MallMotoColor
    {
        public int ID { get; set; }
        public string ColorNameTR { get; set; }
        public string ColorNameEN { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
