//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MallLocationContract
    {
        public int ID { get; set; }
        public Nullable<int> MallID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string LocationDescription { get; set; }
        public Nullable<double> RentAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<double> CommonExpenseAmount { get; set; }
        public Nullable<double> GuaranteeAmount { get; set; }
        public Nullable<double> StampDutyAmount { get; set; }
        public string ContractDuration { get; set; }
        public Nullable<System.DateTime> ContractDateBegin { get; set; }
        public Nullable<System.DateTime> ContractDateEnd { get; set; }
        public string ContractFile { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
