//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileLoginLog
    {
        public int Id { get; set; }
        public string DeviceID { get; set; }
        public string Username { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string TimeZone { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string Message { get; set; }
        public string MessageError { get; set; }
    }
}
