//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileLog
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string Ip { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string Message { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Params { get; set; }
        public string ReturnObject { get; set; }
    }
}
