//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ActionTimeEntities : DbContext
    {
        public ActionTimeEntities()
            : base("name=ActionTimeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<ActionAccounts> ActionAccounts { get; set; }
        public virtual DbSet<ActionRow> ActionRow { get; set; }
        public virtual DbSet<ActionRowDocument> ActionRowDocument { get; set; }
        public virtual DbSet<ActionRowExpense> ActionRowExpense { get; set; }
        public virtual DbSet<ActionRowLabors> ActionRowLabors { get; set; }
        public virtual DbSet<ActionRowProcess> ActionRowProcess { get; set; }
        public virtual DbSet<ActionRowResult> ActionRowResult { get; set; }
        public virtual DbSet<ActionRowResultChild> ActionRowResultChild { get; set; }
        public virtual DbSet<ActionRowResultCR> ActionRowResultCR { get; set; }
        public virtual DbSet<ActionRowSale> ActionRowSale { get; set; }
        public virtual DbSet<ActionState> ActionState { get; set; }
        public virtual DbSet<ActionType> ActionType { get; set; }
        public virtual DbSet<ActionTypeExpense> ActionTypeExpense { get; set; }
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<AnimalType> AnimalType { get; set; }
        public virtual DbSet<AuthorizedIP> AuthorizedIP { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<BankAccount> BankAccount { get; set; }
        public virtual DbSet<BankAccountType> BankAccountType { get; set; }
        public virtual DbSet<BankActionType> BankActionType { get; set; }
        public virtual DbSet<BankNotification> BankNotification { get; set; }
        public virtual DbSet<BankNotificationStatus> BankNotificationStatus { get; set; }
        public virtual DbSet<BreakTypes> BreakTypes { get; set; }
        public virtual DbSet<Cash> Cash { get; set; }
        public virtual DbSet<CashActionType> CashActionType { get; set; }
        public virtual DbSet<Chassis> Chassis { get; set; }
        public virtual DbSet<ChassisType> ChassisType { get; set; }
        public virtual DbSet<CheckParameters> CheckParameters { get; set; }
        public virtual DbSet<Costume> Costume { get; set; }
        public virtual DbSet<CostumeType> CostumeType { get; set; }
        public virtual DbSet<DateList> DateList { get; set; }
        public virtual DbSet<DocumentNumber> DocumentNumber { get; set; }
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<EmployeeCashActions> EmployeeCashActions { get; set; }
        public virtual DbSet<EmployeeDismissal> EmployeeDismissal { get; set; }
        public virtual DbSet<EmployeeDismissalStage> EmployeeDismissalStage { get; set; }
        public virtual DbSet<EmployeeLocation> EmployeeLocation { get; set; }
        public virtual DbSet<EmployeeSalary> EmployeeSalary { get; set; }
        public virtual DbSet<EmployeeShift> EmployeeShift { get; set; }
        public virtual DbSet<EmployeeShiftSet> EmployeeShiftSet { get; set; }
        public virtual DbSet<Inspection> Inspection { get; set; }
        public virtual DbSet<InspectionCategory> InspectionCategory { get; set; }
        public virtual DbSet<InspectionItem> InspectionItem { get; set; }
        public virtual DbSet<InspectorReport> InspectorReport { get; set; }
        public virtual DbSet<InspectorReportEmployee> InspectorReportEmployee { get; set; }
        public virtual DbSet<InspectorReportEmployeeRows> InspectorReportEmployeeRows { get; set; }
        public virtual DbSet<InspectorReportKey> InspectorReportKey { get; set; }
        public virtual DbSet<InspectorReportKeyCategory> InspectorReportKeyCategory { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<LocationAnimals> LocationAnimals { get; set; }
        public virtual DbSet<LocationCR> LocationCR { get; set; }
        public virtual DbSet<LocationParam> LocationParam { get; set; }
        public virtual DbSet<LocationShift> LocationShift { get; set; }
        public virtual DbSet<LocationShiftSet> LocationShiftSet { get; set; }
        public virtual DbSet<LocationShiftSetClose> LocationShiftSetClose { get; set; }
        public virtual DbSet<LocationStats> LocationStats { get; set; }
        public virtual DbSet<LocationTicketType> LocationTicketType { get; set; }
        public virtual DbSet<LocationTrampoline> LocationTrampoline { get; set; }
        public virtual DbSet<LocationType> LocationType { get; set; }
        public virtual DbSet<LocationWareHouse> LocationWareHouse { get; set; }
        public virtual DbSet<LoginLog> LoginLog { get; set; }
        public virtual DbSet<MobileLog> MobileLog { get; set; }
        public virtual DbSet<MobileLoginLog> MobileLoginLog { get; set; }
        public virtual DbSet<OurCompany> OurCompany { get; set; }
        public virtual DbSet<OurCompanyPartner> OurCompanyPartner { get; set; }
        public virtual DbSet<PayMethod> PayMethod { get; set; }
        public virtual DbSet<PerformanceCategory> PerformanceCategory { get; set; }
        public virtual DbSet<PerformanceCriteria> PerformanceCriteria { get; set; }
        public virtual DbSet<PerformanceX> PerformanceX { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<PrePaidCampaign> PrePaidCampaign { get; set; }
        public virtual DbSet<PrePaidCampaignPrices> PrePaidCampaignPrices { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<PromotionBlackOut> PromotionBlackOut { get; set; }
        public virtual DbSet<PromotionLocations> PromotionLocations { get; set; }
        public virtual DbSet<PromotionRule> PromotionRule { get; set; }
        public virtual DbSet<Promotions> Promotions { get; set; }
        public virtual DbSet<RecordNumber> RecordNumber { get; set; }
        public virtual DbSet<RefundTypes> RefundTypes { get; set; }
        public virtual DbSet<ResultState> ResultState { get; set; }
        public virtual DbSet<Resultstatus> Resultstatus { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleGroup> RoleGroup { get; set; }
        public virtual DbSet<RoleGroupMembers> RoleGroupMembers { get; set; }
        public virtual DbSet<RoleGroupPermissions> RoleGroupPermissions { get; set; }
        public virtual DbSet<RoleLevel> RoleLevel { get; set; }
        public virtual DbSet<SaleChannel> SaleChannel { get; set; }
        public virtual DbSet<Serials> Serials { get; set; }
        public virtual DbSet<SerialsHistory> SerialsHistory { get; set; }
        public virtual DbSet<SMSNumber> SMSNumber { get; set; }
        public virtual DbSet<Stats> Stats { get; set; }
        public virtual DbSet<StatsOptions> StatsOptions { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<TaskCategory> TaskCategory { get; set; }
        public virtual DbSet<TicketBasket> TicketBasket { get; set; }
        public virtual DbSet<TicketConfirm> TicketConfirm { get; set; }
        public virtual DbSet<TicketConfirmRows> TicketConfirmRows { get; set; }
        public virtual DbSet<TicketEmployee> TicketEmployee { get; set; }
        public virtual DbSet<TicketEnvironment> TicketEnvironment { get; set; }
        public virtual DbSet<TicketPrice> TicketPrice { get; set; }
        public virtual DbSet<TicketPriceCategory> TicketPriceCategory { get; set; }
        public virtual DbSet<TicketPromotion> TicketPromotion { get; set; }
        public virtual DbSet<TicketPromotionCalender> TicketPromotionCalender { get; set; }
        public virtual DbSet<TicketPromotionLocations> TicketPromotionLocations { get; set; }
        public virtual DbSet<TicketPromotionStatus> TicketPromotionStatus { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<TicketSale> TicketSale { get; set; }
        public virtual DbSet<TicketSaleLines> TicketSaleLines { get; set; }
        public virtual DbSet<TicketSaleRefund> TicketSaleRefund { get; set; }
        public virtual DbSet<TicketSaleRowHistory> TicketSaleRowHistory { get; set; }
        public virtual DbSet<TicketSaleRows> TicketSaleRows { get; set; }
        public virtual DbSet<TicketSaleTransfer> TicketSaleTransfer { get; set; }
        public virtual DbSet<TicketSaleType> TicketSaleType { get; set; }
        public virtual DbSet<TicketStatus> TicketStatus { get; set; }
        public virtual DbSet<TicketStatusChanges> TicketStatusChanges { get; set; }
        public virtual DbSet<TicketTrip> TicketTrip { get; set; }
        public virtual DbSet<TicketTripConfirm> TicketTripConfirm { get; set; }
        public virtual DbSet<TicketType> TicketType { get; set; }
        public virtual DbSet<Trampoline> Trampoline { get; set; }
        public virtual DbSet<TrampolinePart> TrampolinePart { get; set; }
        public virtual DbSet<TrampolinePartType> TrampolinePartType { get; set; }
        public virtual DbSet<TrampolineType> TrampolineType { get; set; }
        public virtual DbSet<EmployeeShiftX> EmployeeShiftX { get; set; }
        public virtual DbSet<EmployeeX> EmployeeX { get; set; }
        public virtual DbSet<VEmployee> VEmployee { get; set; }
        public virtual DbSet<VLocation> VLocation { get; set; }
        public virtual DbSet<DocumentCashCollections> DocumentCashCollections { get; set; }
        public virtual DbSet<DocumentCashExpense> DocumentCashExpense { get; set; }
        public virtual DbSet<DocumentCashPayments> DocumentCashPayments { get; set; }
        public virtual DbSet<DocumentPosCollections> DocumentPosCollections { get; set; }
        public virtual DbSet<DocumentSaleExchange> DocumentSaleExchange { get; set; }
        public virtual DbSet<DocumentTicketSaleReturns> DocumentTicketSaleReturns { get; set; }
        public virtual DbSet<DocumentTicketSales> DocumentTicketSales { get; set; }
        public virtual DbSet<DocumentSalaryEarn> DocumentSalaryEarn { get; set; }
        public virtual DbSet<VDocumentCashCollections> VDocumentCashCollections { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Exchange> Exchange { get; set; }
        public virtual DbSet<BankActions> BankActions { get; set; }
        public virtual DbSet<CashActions> CashActions { get; set; }
        public virtual DbSet<VBankActions> VBankActions { get; set; }
        public virtual DbSet<VCashActions> VCashActions { get; set; }
        public virtual DbSet<VCashBankActions> VCashBankActions { get; set; }
        public virtual DbSet<VDocumentTicketSales> VDocumentTicketSales { get; set; }
        public virtual DbSet<VDocumentSaleExchange> VDocumentSaleExchange { get; set; }
        public virtual DbSet<DocumentCashOpen> DocumentCashOpen { get; set; }
        public virtual DbSet<VDocumentCashOpen> VDocumentCashOpen { get; set; }
        public virtual DbSet<VDocumentCashPayments> VDocumentCashPayments { get; set; }
        public virtual DbSet<VDocumentTicketSaleReturn> VDocumentTicketSaleReturn { get; set; }
        public virtual DbSet<Environment> Environment { get; set; }
        public virtual DbSet<VDocumentCashExpense> VDocumentCashExpense { get; set; }
        public virtual DbSet<ExpenseType> ExpenseType { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<VDocumentPosCollection> VDocumentPosCollection { get; set; }
        public virtual DbSet<VLocationSchedule> VLocationSchedule { get; set; }
        public virtual DbSet<WeekList> WeekList { get; set; }
        public virtual DbSet<LocationSchedule> LocationSchedule { get; set; }
        public virtual DbSet<VSchedule> VSchedule { get; set; }
        public virtual DbSet<DayResult> DayResult { get; set; }
        public virtual DbSet<DayResultDocuments> DayResultDocuments { get; set; }
        public virtual DbSet<DayResultItemList> DayResultItemList { get; set; }
        public virtual DbSet<DayResultItems> DayResultItems { get; set; }
        public virtual DbSet<VDayResult> VDayResult { get; set; }
        public virtual DbSet<ApplicationLog> ApplicationLog { get; set; }
        public virtual DbSet<VLocationShift> VLocationShift { get; set; }
        public virtual DbSet<DocumentPosCancel> DocumentPosCancel { get; set; }
        public virtual DbSet<DocumentPosRefund> DocumentPosRefund { get; set; }
        public virtual DbSet<VDocumentPosCancel> VDocumentPosCancel { get; set; }
        public virtual DbSet<VDocumentPosRefund> VDocumentPosRefund { get; set; }
        public virtual DbSet<VDayResultItemList> VDayResultItemList { get; set; }
        public virtual DbSet<VDocumentSalaryEarn> VDocumentSalaryEarn { get; set; }
        public virtual DbSet<VEmployeeSalary> VEmployeeSalary { get; set; }
        public virtual DbSet<VEmployeeSalaryDist> VEmployeeSalaryDist { get; set; }
        public virtual DbSet<CashRecorders> CashRecorders { get; set; }
        public virtual DbSet<LocationPosTerminal> LocationPosTerminal { get; set; }
        public virtual DbSet<PosTerminal> PosTerminal { get; set; }
        public virtual DbSet<VCashRecorders> VCashRecorders { get; set; }
        public virtual DbSet<VPosTerminal> VPosTerminal { get; set; }
        public virtual DbSet<VLocationPosTerminal> VLocationPosTerminal { get; set; }
        public virtual DbSet<BankTransferStatus> BankTransferStatus { get; set; }
        public virtual DbSet<DocumentBankTransfer> DocumentBankTransfer { get; set; }
        public virtual DbSet<VDocumentBankTransfer> VDocumentBankTransfer { get; set; }
        public virtual DbSet<VEmployeeCashActions> VEmployeeCashActions { get; set; }
        public virtual DbSet<VDayResultDocuments> VDayResultDocuments { get; set; }
        public virtual DbSet<LocationGoals> LocationGoals { get; set; }
        public virtual DbSet<SalaryCategory> SalaryCategory { get; set; }
        public virtual DbSet<Setcards> Setcards { get; set; }
        public virtual DbSet<SetcardSubscription> SetcardSubscription { get; set; }
        public virtual DbSet<SetcardSubscriptionType> SetcardSubscriptionType { get; set; }
        public virtual DbSet<DocumentCashRecorderSlip> DocumentCashRecorderSlip { get; set; }
        public virtual DbSet<VDocumentCashRecorderSlip> VDocumentCashRecorderSlip { get; set; }
        public virtual DbSet<DocumentTransfer> DocumentTransfer { get; set; }
        public virtual DbSet<VDocumentTransfer> VDocumentTransfer { get; set; }
        public virtual DbSet<VCash> VCash { get; set; }
        public virtual DbSet<DocumentTransferStatus> DocumentTransferStatus { get; set; }
        public virtual DbSet<VEmployeeLocation> VEmployeeLocation { get; set; }
        public virtual DbSet<VEmployeeLocationList> VEmployeeLocationList { get; set; }
        public virtual DbSet<SetcardParameter> SetcardParameter { get; set; }
        public virtual DbSet<CustomerActions> CustomerActions { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeAreaCategory> EmployeeAreaCategory { get; set; }
        public virtual DbSet<EmployeePositions> EmployeePositions { get; set; }
        public virtual DbSet<EmployeeSalaryCategory> EmployeeSalaryCategory { get; set; }
        public virtual DbSet<EmployeeSequence> EmployeeSequence { get; set; }
        public virtual DbSet<EmployeeShiftType> EmployeeShiftType { get; set; }
        public virtual DbSet<EmployeeStatus> EmployeeStatus { get; set; }
        public virtual DbSet<PermitStatus> PermitStatus { get; set; }
        public virtual DbSet<PermitType> PermitType { get; set; }
        public virtual DbSet<DocumentEmployeePermit> DocumentEmployeePermit { get; set; }
        public virtual DbSet<VDocumentEmployeePermit> VDocumentEmployeePermit { get; set; }
        public virtual DbSet<SalaryType> SalaryType { get; set; }
        public virtual DbSet<DocumentSalaryPayment> DocumentSalaryPayment { get; set; }
        public virtual DbSet<VDocumentSalaryPayment> VDocumentSalaryPayment { get; set; }
        public virtual DbSet<VEmployeeList> VEmployeeList { get; set; }
        public virtual DbSet<VBankAccount> VBankAccount { get; set; }
        public virtual DbSet<IdentityType> IdentityType { get; set; }
        public virtual DbSet<LocationPeriods> LocationPeriods { get; set; }
        public virtual DbSet<EmployeePeriods> EmployeePeriods { get; set; }
        public virtual DbSet<Revenue> Revenue { get; set; }
    
        public virtual ObjectResult<GetFromList_Result> GetFromList(Nullable<int> ourCompanyID)
        {
            var ourCompanyIDParameter = ourCompanyID.HasValue ?
                new ObjectParameter("OurCompanyID", ourCompanyID) :
                new ObjectParameter("OurCompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFromList_Result>("GetFromList", ourCompanyIDParameter);
        }
    
        public virtual ObjectResult<string> GetDocumentNumber(Nullable<int> ourCompanyID, string prefix)
        {
            var ourCompanyIDParameter = ourCompanyID.HasValue ?
                new ObjectParameter("OurCompanyID", ourCompanyID) :
                new ObjectParameter("OurCompanyID", typeof(int));
    
            var prefixParameter = prefix != null ?
                new ObjectParameter("Prefix", prefix) :
                new ObjectParameter("Prefix", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetDocumentNumber", ourCompanyIDParameter, prefixParameter);
        }
    
        public virtual ObjectResult<GetToList_Result> GetToList(Nullable<int> ourCompanyID)
        {
            var ourCompanyIDParameter = ourCompanyID.HasValue ?
                new ObjectParameter("OurCompanyID", ourCompanyID) :
                new ObjectParameter("OurCompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetToList_Result>("GetToList", ourCompanyIDParameter);
        }
    
        public virtual ObjectResult<GetPersonList_Result> GetPersonList(Nullable<int> ourCompanyID)
        {
            var ourCompanyIDParameter = ourCompanyID.HasValue ?
                new ObjectParameter("OurCompanyID", ourCompanyID) :
                new ObjectParameter("OurCompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPersonList_Result>("GetPersonList", ourCompanyIDParameter);
        }
    
        public virtual int UpdateCashAction(Nullable<int> cashID, Nullable<int> locationID, Nullable<int> employeeID, Nullable<int> cashActionTypeID, Nullable<System.DateTime> actionDate, string processName, Nullable<long> processID, Nullable<System.DateTime> processDate, string documentNumber, string description, Nullable<short> direction, Nullable<double> collection, Nullable<double> payment, string currency, Nullable<double> latitude, Nullable<double> longitude, Nullable<int> recordEmployeeID, Nullable<System.DateTime> recordDate, Nullable<int> updateEmployeeID, Nullable<System.DateTime> updateDate)
        {
            var cashIDParameter = cashID.HasValue ?
                new ObjectParameter("CashID", cashID) :
                new ObjectParameter("CashID", typeof(int));
    
            var locationIDParameter = locationID.HasValue ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(int));
    
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            var cashActionTypeIDParameter = cashActionTypeID.HasValue ?
                new ObjectParameter("CashActionTypeID", cashActionTypeID) :
                new ObjectParameter("CashActionTypeID", typeof(int));
    
            var actionDateParameter = actionDate.HasValue ?
                new ObjectParameter("ActionDate", actionDate) :
                new ObjectParameter("ActionDate", typeof(System.DateTime));
    
            var processNameParameter = processName != null ?
                new ObjectParameter("ProcessName", processName) :
                new ObjectParameter("ProcessName", typeof(string));
    
            var processIDParameter = processID.HasValue ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(long));
    
            var processDateParameter = processDate.HasValue ?
                new ObjectParameter("ProcessDate", processDate) :
                new ObjectParameter("ProcessDate", typeof(System.DateTime));
    
            var documentNumberParameter = documentNumber != null ?
                new ObjectParameter("DocumentNumber", documentNumber) :
                new ObjectParameter("DocumentNumber", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var directionParameter = direction.HasValue ?
                new ObjectParameter("Direction", direction) :
                new ObjectParameter("Direction", typeof(short));
    
            var collectionParameter = collection.HasValue ?
                new ObjectParameter("Collection", collection) :
                new ObjectParameter("Collection", typeof(double));
    
            var paymentParameter = payment.HasValue ?
                new ObjectParameter("Payment", payment) :
                new ObjectParameter("Payment", typeof(double));
    
            var currencyParameter = currency != null ?
                new ObjectParameter("Currency", currency) :
                new ObjectParameter("Currency", typeof(string));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(double));
    
            var recordEmployeeIDParameter = recordEmployeeID.HasValue ?
                new ObjectParameter("RecordEmployeeID", recordEmployeeID) :
                new ObjectParameter("RecordEmployeeID", typeof(int));
    
            var recordDateParameter = recordDate.HasValue ?
                new ObjectParameter("RecordDate", recordDate) :
                new ObjectParameter("RecordDate", typeof(System.DateTime));
    
            var updateEmployeeIDParameter = updateEmployeeID.HasValue ?
                new ObjectParameter("UpdateEmployeeID", updateEmployeeID) :
                new ObjectParameter("UpdateEmployeeID", typeof(int));
    
            var updateDateParameter = updateDate.HasValue ?
                new ObjectParameter("UpdateDate", updateDate) :
                new ObjectParameter("UpdateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCashAction", cashIDParameter, locationIDParameter, employeeIDParameter, cashActionTypeIDParameter, actionDateParameter, processNameParameter, processIDParameter, processDateParameter, documentNumberParameter, descriptionParameter, directionParameter, collectionParameter, paymentParameter, currencyParameter, latitudeParameter, longitudeParameter, recordEmployeeIDParameter, recordDateParameter, updateEmployeeIDParameter, updateDateParameter);
        }
    
        public virtual int AddApplicationLog(string environment, string modul, string processType, string processID, string controller, string action, string tableName, string fieldName, string oldValue, string newValue, Nullable<bool> isSuccess, string resultMessage, string errorMessage, Nullable<System.DateTime> recordDate, string recordEmployee, string recordIP, string recordDevice, string data)
        {
            var environmentParameter = environment != null ?
                new ObjectParameter("Environment", environment) :
                new ObjectParameter("Environment", typeof(string));
    
            var modulParameter = modul != null ?
                new ObjectParameter("Modul", modul) :
                new ObjectParameter("Modul", typeof(string));
    
            var processTypeParameter = processType != null ?
                new ObjectParameter("ProcessType", processType) :
                new ObjectParameter("ProcessType", typeof(string));
    
            var processIDParameter = processID != null ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(string));
    
            var controllerParameter = controller != null ?
                new ObjectParameter("Controller", controller) :
                new ObjectParameter("Controller", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var oldValueParameter = oldValue != null ?
                new ObjectParameter("OldValue", oldValue) :
                new ObjectParameter("OldValue", typeof(string));
    
            var newValueParameter = newValue != null ?
                new ObjectParameter("NewValue", newValue) :
                new ObjectParameter("NewValue", typeof(string));
    
            var isSuccessParameter = isSuccess.HasValue ?
                new ObjectParameter("IsSuccess", isSuccess) :
                new ObjectParameter("IsSuccess", typeof(bool));
    
            var resultMessageParameter = resultMessage != null ?
                new ObjectParameter("ResultMessage", resultMessage) :
                new ObjectParameter("ResultMessage", typeof(string));
    
            var errorMessageParameter = errorMessage != null ?
                new ObjectParameter("ErrorMessage", errorMessage) :
                new ObjectParameter("ErrorMessage", typeof(string));
    
            var recordDateParameter = recordDate.HasValue ?
                new ObjectParameter("RecordDate", recordDate) :
                new ObjectParameter("RecordDate", typeof(System.DateTime));
    
            var recordEmployeeParameter = recordEmployee != null ?
                new ObjectParameter("RecordEmployee", recordEmployee) :
                new ObjectParameter("RecordEmployee", typeof(string));
    
            var recordIPParameter = recordIP != null ?
                new ObjectParameter("RecordIP", recordIP) :
                new ObjectParameter("RecordIP", typeof(string));
    
            var recordDeviceParameter = recordDevice != null ?
                new ObjectParameter("RecordDevice", recordDevice) :
                new ObjectParameter("RecordDevice", typeof(string));
    
            var dataParameter = data != null ?
                new ObjectParameter("Data", data) :
                new ObjectParameter("Data", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddApplicationLog", environmentParameter, modulParameter, processTypeParameter, processIDParameter, controllerParameter, actionParameter, tableNameParameter, fieldNameParameter, oldValueParameter, newValueParameter, isSuccessParameter, resultMessageParameter, errorMessageParameter, recordDateParameter, recordEmployeeParameter, recordIPParameter, recordDeviceParameter, dataParameter);
        }
    
        public virtual int SetShiftDates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetShiftDates");
        }
    
        public virtual ObjectResult<Nullable<double>> GetCashBalance(Nullable<int> locationID, Nullable<int> cashID, Nullable<System.DateTime> date)
        {
            var locationIDParameter = locationID.HasValue ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(int));
    
            var cashIDParameter = cashID.HasValue ?
                new ObjectParameter("CashID", cashID) :
                new ObjectParameter("CashID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("GetCashBalance", locationIDParameter, cashIDParameter, dateParameter);
        }
    
        public virtual int SetLocationSchedules(Nullable<int> ourCompanyID, Nullable<int> year, Nullable<int> weekNumber, Nullable<int> employeeID)
        {
            var ourCompanyIDParameter = ourCompanyID.HasValue ?
                new ObjectParameter("OurCompanyID", ourCompanyID) :
                new ObjectParameter("OurCompanyID", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var weekNumberParameter = weekNumber.HasValue ?
                new ObjectParameter("WeekNumber", weekNumber) :
                new ObjectParameter("WeekNumber", typeof(int));
    
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetLocationSchedules", ourCompanyIDParameter, yearParameter, weekNumberParameter, employeeIDParameter);
        }
    
        public virtual int AddBankAction(Nullable<int> locationID, Nullable<int> employeeID, Nullable<int> bankAccountID, Nullable<int> posID, Nullable<int> bankActionTypeID, Nullable<System.DateTime> actionDate, string processName, Nullable<long> processID, Nullable<System.DateTime> processDate, string documentNumber, string description, Nullable<short> direction, Nullable<double> collection, Nullable<double> payment, string currency, Nullable<double> latitude, Nullable<double> longitude, Nullable<int> recordEmployeeID, Nullable<System.DateTime> recordDate, Nullable<System.Guid> processUID)
        {
            var locationIDParameter = locationID.HasValue ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(int));
    
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            var bankAccountIDParameter = bankAccountID.HasValue ?
                new ObjectParameter("BankAccountID", bankAccountID) :
                new ObjectParameter("BankAccountID", typeof(int));
    
            var posIDParameter = posID.HasValue ?
                new ObjectParameter("PosID", posID) :
                new ObjectParameter("PosID", typeof(int));
    
            var bankActionTypeIDParameter = bankActionTypeID.HasValue ?
                new ObjectParameter("BankActionTypeID", bankActionTypeID) :
                new ObjectParameter("BankActionTypeID", typeof(int));
    
            var actionDateParameter = actionDate.HasValue ?
                new ObjectParameter("ActionDate", actionDate) :
                new ObjectParameter("ActionDate", typeof(System.DateTime));
    
            var processNameParameter = processName != null ?
                new ObjectParameter("ProcessName", processName) :
                new ObjectParameter("ProcessName", typeof(string));
    
            var processIDParameter = processID.HasValue ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(long));
    
            var processDateParameter = processDate.HasValue ?
                new ObjectParameter("ProcessDate", processDate) :
                new ObjectParameter("ProcessDate", typeof(System.DateTime));
    
            var documentNumberParameter = documentNumber != null ?
                new ObjectParameter("DocumentNumber", documentNumber) :
                new ObjectParameter("DocumentNumber", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var directionParameter = direction.HasValue ?
                new ObjectParameter("Direction", direction) :
                new ObjectParameter("Direction", typeof(short));
    
            var collectionParameter = collection.HasValue ?
                new ObjectParameter("Collection", collection) :
                new ObjectParameter("Collection", typeof(double));
    
            var paymentParameter = payment.HasValue ?
                new ObjectParameter("Payment", payment) :
                new ObjectParameter("Payment", typeof(double));
    
            var currencyParameter = currency != null ?
                new ObjectParameter("Currency", currency) :
                new ObjectParameter("Currency", typeof(string));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(double));
    
            var recordEmployeeIDParameter = recordEmployeeID.HasValue ?
                new ObjectParameter("RecordEmployeeID", recordEmployeeID) :
                new ObjectParameter("RecordEmployeeID", typeof(int));
    
            var recordDateParameter = recordDate.HasValue ?
                new ObjectParameter("RecordDate", recordDate) :
                new ObjectParameter("RecordDate", typeof(System.DateTime));
    
            var processUIDParameter = processUID.HasValue ?
                new ObjectParameter("ProcessUID", processUID) :
                new ObjectParameter("ProcessUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddBankAction", locationIDParameter, employeeIDParameter, bankAccountIDParameter, posIDParameter, bankActionTypeIDParameter, actionDateParameter, processNameParameter, processIDParameter, processDateParameter, documentNumberParameter, descriptionParameter, directionParameter, collectionParameter, paymentParameter, currencyParameter, latitudeParameter, longitudeParameter, recordEmployeeIDParameter, recordDateParameter, processUIDParameter);
        }
    
        public virtual int AddCashAction(Nullable<int> cashID, Nullable<int> locationID, Nullable<int> employeeID, Nullable<int> cashActionTypeID, Nullable<System.DateTime> actionDate, string processName, Nullable<long> processID, Nullable<System.DateTime> processDate, string documentNumber, string description, Nullable<short> direction, Nullable<double> collection, Nullable<double> payment, string currency, Nullable<double> latitude, Nullable<double> longitude, Nullable<int> recordEmployeeID, Nullable<System.DateTime> recordDate, Nullable<System.Guid> processUID)
        {
            var cashIDParameter = cashID.HasValue ?
                new ObjectParameter("CashID", cashID) :
                new ObjectParameter("CashID", typeof(int));
    
            var locationIDParameter = locationID.HasValue ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(int));
    
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            var cashActionTypeIDParameter = cashActionTypeID.HasValue ?
                new ObjectParameter("CashActionTypeID", cashActionTypeID) :
                new ObjectParameter("CashActionTypeID", typeof(int));
    
            var actionDateParameter = actionDate.HasValue ?
                new ObjectParameter("ActionDate", actionDate) :
                new ObjectParameter("ActionDate", typeof(System.DateTime));
    
            var processNameParameter = processName != null ?
                new ObjectParameter("ProcessName", processName) :
                new ObjectParameter("ProcessName", typeof(string));
    
            var processIDParameter = processID.HasValue ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(long));
    
            var processDateParameter = processDate.HasValue ?
                new ObjectParameter("ProcessDate", processDate) :
                new ObjectParameter("ProcessDate", typeof(System.DateTime));
    
            var documentNumberParameter = documentNumber != null ?
                new ObjectParameter("DocumentNumber", documentNumber) :
                new ObjectParameter("DocumentNumber", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var directionParameter = direction.HasValue ?
                new ObjectParameter("Direction", direction) :
                new ObjectParameter("Direction", typeof(short));
    
            var collectionParameter = collection.HasValue ?
                new ObjectParameter("Collection", collection) :
                new ObjectParameter("Collection", typeof(double));
    
            var paymentParameter = payment.HasValue ?
                new ObjectParameter("Payment", payment) :
                new ObjectParameter("Payment", typeof(double));
    
            var currencyParameter = currency != null ?
                new ObjectParameter("Currency", currency) :
                new ObjectParameter("Currency", typeof(string));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(double));
    
            var recordEmployeeIDParameter = recordEmployeeID.HasValue ?
                new ObjectParameter("RecordEmployeeID", recordEmployeeID) :
                new ObjectParameter("RecordEmployeeID", typeof(int));
    
            var recordDateParameter = recordDate.HasValue ?
                new ObjectParameter("RecordDate", recordDate) :
                new ObjectParameter("RecordDate", typeof(System.DateTime));
    
            var processUIDParameter = processUID.HasValue ?
                new ObjectParameter("ProcessUID", processUID) :
                new ObjectParameter("ProcessUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddCashAction", cashIDParameter, locationIDParameter, employeeIDParameter, cashActionTypeIDParameter, actionDateParameter, processNameParameter, processIDParameter, processDateParameter, documentNumberParameter, descriptionParameter, directionParameter, collectionParameter, paymentParameter, currencyParameter, latitudeParameter, longitudeParameter, recordEmployeeIDParameter, recordDateParameter, processUIDParameter);
        }
    
        public virtual int AddEmployeeAction(Nullable<int> employeeID, Nullable<int> locationID, Nullable<int> actionTypeID, string processName, Nullable<long> processID, Nullable<System.DateTime> processDate, string processDetail, Nullable<short> direction, Nullable<double> collection, Nullable<double> payment, string currency, Nullable<double> latitude, Nullable<double> longitude, Nullable<int> salaryTypeID, Nullable<int> recordEmployeeID, Nullable<System.DateTime> recordDate, Nullable<System.Guid> processUID, string documentNumber, Nullable<int> salaryCategoryID)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            var locationIDParameter = locationID.HasValue ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(int));
    
            var actionTypeIDParameter = actionTypeID.HasValue ?
                new ObjectParameter("ActionTypeID", actionTypeID) :
                new ObjectParameter("ActionTypeID", typeof(int));
    
            var processNameParameter = processName != null ?
                new ObjectParameter("ProcessName", processName) :
                new ObjectParameter("ProcessName", typeof(string));
    
            var processIDParameter = processID.HasValue ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(long));
    
            var processDateParameter = processDate.HasValue ?
                new ObjectParameter("ProcessDate", processDate) :
                new ObjectParameter("ProcessDate", typeof(System.DateTime));
    
            var processDetailParameter = processDetail != null ?
                new ObjectParameter("ProcessDetail", processDetail) :
                new ObjectParameter("ProcessDetail", typeof(string));
    
            var directionParameter = direction.HasValue ?
                new ObjectParameter("Direction", direction) :
                new ObjectParameter("Direction", typeof(short));
    
            var collectionParameter = collection.HasValue ?
                new ObjectParameter("Collection", collection) :
                new ObjectParameter("Collection", typeof(double));
    
            var paymentParameter = payment.HasValue ?
                new ObjectParameter("Payment", payment) :
                new ObjectParameter("Payment", typeof(double));
    
            var currencyParameter = currency != null ?
                new ObjectParameter("Currency", currency) :
                new ObjectParameter("Currency", typeof(string));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(double));
    
            var salaryTypeIDParameter = salaryTypeID.HasValue ?
                new ObjectParameter("SalaryTypeID", salaryTypeID) :
                new ObjectParameter("SalaryTypeID", typeof(int));
    
            var recordEmployeeIDParameter = recordEmployeeID.HasValue ?
                new ObjectParameter("RecordEmployeeID", recordEmployeeID) :
                new ObjectParameter("RecordEmployeeID", typeof(int));
    
            var recordDateParameter = recordDate.HasValue ?
                new ObjectParameter("RecordDate", recordDate) :
                new ObjectParameter("RecordDate", typeof(System.DateTime));
    
            var processUIDParameter = processUID.HasValue ?
                new ObjectParameter("ProcessUID", processUID) :
                new ObjectParameter("ProcessUID", typeof(System.Guid));
    
            var documentNumberParameter = documentNumber != null ?
                new ObjectParameter("DocumentNumber", documentNumber) :
                new ObjectParameter("DocumentNumber", typeof(string));
    
            var salaryCategoryIDParameter = salaryCategoryID.HasValue ?
                new ObjectParameter("SalaryCategoryID", salaryCategoryID) :
                new ObjectParameter("SalaryCategoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddEmployeeAction", employeeIDParameter, locationIDParameter, actionTypeIDParameter, processNameParameter, processIDParameter, processDateParameter, processDetailParameter, directionParameter, collectionParameter, paymentParameter, currencyParameter, latitudeParameter, longitudeParameter, salaryTypeIDParameter, recordEmployeeIDParameter, recordDateParameter, processUIDParameter, documentNumberParameter, salaryCategoryIDParameter);
        }
    
        public virtual int AddCustomerAction(Nullable<int> customerID, Nullable<int> locationID, Nullable<int> employeeID, Nullable<int> actionTypeID, Nullable<System.DateTime> actionDate, string processName, Nullable<long> processID, Nullable<System.DateTime> processDate, string documentNumber, string description, Nullable<short> direction, Nullable<double> collection, Nullable<double> payment, string currency, Nullable<double> latitude, Nullable<double> longitude, Nullable<int> recordEmployeeID, Nullable<System.DateTime> recordDate, Nullable<System.Guid> processUID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var locationIDParameter = locationID.HasValue ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(int));
    
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            var actionTypeIDParameter = actionTypeID.HasValue ?
                new ObjectParameter("ActionTypeID", actionTypeID) :
                new ObjectParameter("ActionTypeID", typeof(int));
    
            var actionDateParameter = actionDate.HasValue ?
                new ObjectParameter("ActionDate", actionDate) :
                new ObjectParameter("ActionDate", typeof(System.DateTime));
    
            var processNameParameter = processName != null ?
                new ObjectParameter("ProcessName", processName) :
                new ObjectParameter("ProcessName", typeof(string));
    
            var processIDParameter = processID.HasValue ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(long));
    
            var processDateParameter = processDate.HasValue ?
                new ObjectParameter("ProcessDate", processDate) :
                new ObjectParameter("ProcessDate", typeof(System.DateTime));
    
            var documentNumberParameter = documentNumber != null ?
                new ObjectParameter("DocumentNumber", documentNumber) :
                new ObjectParameter("DocumentNumber", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var directionParameter = direction.HasValue ?
                new ObjectParameter("Direction", direction) :
                new ObjectParameter("Direction", typeof(short));
    
            var collectionParameter = collection.HasValue ?
                new ObjectParameter("Collection", collection) :
                new ObjectParameter("Collection", typeof(double));
    
            var paymentParameter = payment.HasValue ?
                new ObjectParameter("Payment", payment) :
                new ObjectParameter("Payment", typeof(double));
    
            var currencyParameter = currency != null ?
                new ObjectParameter("Currency", currency) :
                new ObjectParameter("Currency", typeof(string));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(double));
    
            var recordEmployeeIDParameter = recordEmployeeID.HasValue ?
                new ObjectParameter("RecordEmployeeID", recordEmployeeID) :
                new ObjectParameter("RecordEmployeeID", typeof(int));
    
            var recordDateParameter = recordDate.HasValue ?
                new ObjectParameter("RecordDate", recordDate) :
                new ObjectParameter("RecordDate", typeof(System.DateTime));
    
            var processUIDParameter = processUID.HasValue ?
                new ObjectParameter("ProcessUID", processUID) :
                new ObjectParameter("ProcessUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddCustomerAction", customerIDParameter, locationIDParameter, employeeIDParameter, actionTypeIDParameter, actionDateParameter, processNameParameter, processIDParameter, processDateParameter, documentNumberParameter, descriptionParameter, directionParameter, collectionParameter, paymentParameter, currencyParameter, latitudeParameter, longitudeParameter, recordEmployeeIDParameter, recordDateParameter, processUIDParameter);
        }
    
        public virtual int RemoveAllAccountActions(Nullable<long> processID, Nullable<System.Guid> processUID)
        {
            var processIDParameter = processID.HasValue ?
                new ObjectParameter("ProcessID", processID) :
                new ObjectParameter("ProcessID", typeof(long));
    
            var processUIDParameter = processUID.HasValue ?
                new ObjectParameter("ProcessUID", processUID) :
                new ObjectParameter("ProcessUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RemoveAllAccountActions", processIDParameter, processUIDParameter);
        }
    
        public virtual ObjectResult<GetLocationCurrentSchedule_Result> GetLocationCurrentSchedule(Nullable<int> locationID, Nullable<System.DateTime> date)
        {
            var locationIDParameter = locationID.HasValue ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLocationCurrentSchedule_Result>("GetLocationCurrentSchedule", locationIDParameter, dateParameter);
        }
    
        public virtual ObjectResult<GetLocationCurrentShift_Result> GetLocationCurrentShift(Nullable<int> locationID, Nullable<System.DateTime> date)
        {
            var locationIDParameter = locationID.HasValue ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLocationCurrentShift_Result>("GetLocationCurrentShift", locationIDParameter, dateParameter);
        }
    
        public virtual ObjectResult<GetLocationAll_Result> GetLocationAll(Nullable<int> ourCompanyID)
        {
            var ourCompanyIDParameter = ourCompanyID.HasValue ?
                new ObjectParameter("OurCompanyID", ourCompanyID) :
                new ObjectParameter("OurCompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLocationAll_Result>("GetLocationAll", ourCompanyIDParameter);
        }
    }
}
