//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFCCardLog
    {
        public long ID { get; set; }
        public string Message { get; set; }
        public string RecordIP { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Module { get; set; }
        public string ResponseMessage { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    }
}
