//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurCompanyPartner
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public string PartnerCode { get; set; }
        public string PartnerFullName { get; set; }
        public string Country { get; set; }
        public string Currency { get; set; }
        public string Phone { get; set; }
        public string Web { get; set; }
        public string Eposta { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
