//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurCompany
    {
        public int CompanyID { get; set; }
        public string Code { get; set; }
        public string CompanyName { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> TimeZone { get; set; }
        public string Currency { get; set; }
        public string Weight { get; set; }
        public string Distance { get; set; }
        public string Culture { get; set; }
    }
}
