//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerActions
    {
        public long ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> PartnerID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string ProcessName { get; set; }
        public Nullable<long> ProcessID { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string PeriodCode { get; set; }
        public Nullable<int> ExpenseYear { get; set; }
        public Nullable<int> ExpenseMonth { get; set; }
        public string DocumentNumber { get; set; }
        public string Description { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> PartnershipRate { get; set; }
        public Nullable<double> CapacityRate { get; set; }
        public Nullable<double> Collection { get; set; }
        public Nullable<double> Payment { get; set; }
        public double Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> ProcessUID { get; set; }
        public Nullable<int> ActionTypeID { get; set; }
    }
}
