//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceCriteria
    {
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CriteriaName { get; set; }
        public Nullable<int> Parameter { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> ScoreLive { get; set; }
        public Nullable<int> ScoreCamera { get; set; }
        public Nullable<int> ScoreInspection { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public string SortBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
