//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceX
    {
        public long ID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CriteriaID { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Description { get; set; }
        public Nullable<int> RecordEmplyeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    }
}
