//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrePaidCampaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrePaidCampaign()
        {
            this.PrePaidCampaignPrices = new HashSet<PrePaidCampaignPrices>();
        }
    
        public int ID { get; set; }
        public string CampaignName { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
        public Nullable<System.DateTime> DatePublish { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<double> WeekInDiscount { get; set; }
        public Nullable<double> WeekInCommission { get; set; }
        public Nullable<double> WeekEndDiscount { get; set; }
        public Nullable<double> WeekEndCommission { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual TicketType TicketType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrePaidCampaignPrices> PrePaidCampaignPrices { get; set; }
    }
}
