//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> PriceCategoryID { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<double> Price1 { get; set; }
        public string Currency { get; set; }
        public Nullable<double> ExtraMultiple { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> UseToSale { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public string RecordIP { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public string UpdateIP { get; set; }
    }
}
