//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int StockID { get; set; }
        public string SKU { get; set; }
        public string ProductCode { get; set; }
        public string StockCode { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Barcode { get; set; }
        public string ProductName { get; set; }
        public string Property { get; set; }
        public string PropertyValue { get; set; }
        public Nullable<int> CardTypeID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string UnitCode { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public string MainImage { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public Nullable<bool> IsZeroStock { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<bool> IsEnvanter { get; set; }
        public Nullable<bool> IsTrackSerial { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
