//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int StockID { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string StockCode { get; set; }
        public string Barcode { get; set; }
        public string FullName { get; set; }
        public string Property { get; set; }
        public string Unit { get; set; }
        public Nullable<bool> IsZeroStock { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<bool> IsEnvanter { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
