//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionRule
    {
        public int ID { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public Nullable<int> MainTicketPriceID { get; set; }
        public Nullable<int> MainTicketQuantity { get; set; }
        public Nullable<int> PromTicketPriceID { get; set; }
        public Nullable<int> PromTicketQuantity { get; set; }
        public Nullable<int> PriceCatID { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<bool> Monday { get; set; }
        public Nullable<bool> Tuesday { get; set; }
        public Nullable<bool> Wednesday { get; set; }
        public Nullable<bool> Thursday { get; set; }
        public Nullable<bool> Friday { get; set; }
        public Nullable<bool> Saturday { get; set; }
        public Nullable<bool> Sunday { get; set; }
    }
}
