//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenueParameter
    {
        public int ID { get; set; }
        public int LocationID { get; set; }
        public System.DateTime DateBegin { get; set; }
        public bool IsCash { get; set; }
        public bool IsCredit { get; set; }
        public bool IsRent { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
