//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenueLines
    {
        public long ID { get; set; }
        public Nullable<long> RevenueID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> WeekYear { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> Credit { get; set; }
        public string Currency { get; set; }
        public double Total { get; set; }
        public Nullable<double> Labor { get; set; }
        public Nullable<double> Expense { get; set; }
        public Nullable<double> CashIn { get; set; }
        public Nullable<double> Rent { get; set; }
        public Nullable<double> CommissionRate { get; set; }
        public Nullable<double> CreditCommission { get; set; }
        public Nullable<double> InsuranceRate { get; set; }
        public Nullable<double> Insurance { get; set; }
        public Nullable<double> RentRate { get; set; }
        public Nullable<double> OpDebt { get; set; }
    }
}
