//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleGroupPermissions
    {
        public int ID { get; set; }
        public Nullable<int> RoleGroupID { get; set; }
        public Nullable<int> PermissionID { get; set; }
        public Nullable<bool> IsNavigate { get; set; }
        public Nullable<bool> IsSelect { get; set; }
        public Nullable<bool> IsInsert { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> StatusLevel { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual RoleGroup RoleGroup { get; set; }
    }
}
