//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryPeriodGroup
    {
        public short ID { get; set; }
        public Nullable<short> GroupType { get; set; }
        public string GroupName { get; set; }
        public Nullable<short> DayCount { get; set; }
        public Nullable<int> EmployeeAreaCategoryID { get; set; }
        public Nullable<int> SalaryCategoryID { get; set; }
    }
}
