//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryPeriodComputeActions
    {
        public long ID { get; set; }
        public Nullable<int> SalaryPeriodID { get; set; }
        public Nullable<short> SalaryPeriodStatusID { get; set; }
        public Nullable<long> EmployeeCashActionID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ActionTypeID { get; set; }
        public string DocumentNumber { get; set; }
        public string ProcessName { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string ProcessDetail { get; set; }
        public Nullable<System.Guid> ProcessUID { get; set; }
        public Nullable<short> Direction { get; set; }
        public Nullable<double> Collection { get; set; }
        public Nullable<double> Payment { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<int> SalaryTypeID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
