//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryPeriodCompute
    {
        public long ID { get; set; }
        public Nullable<int> SalaryPeriodID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string FullName { get; set; }
        public string IdentityNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string FoodCard { get; set; }
        public string IBAN { get; set; }
        public string BankName { get; set; }
        public Nullable<double> SalaryTotal { get; set; }
        public Nullable<double> PermitTotal { get; set; }
        public Nullable<double> ExtraShiftTotal { get; set; }
        public Nullable<double> PremiumTotal { get; set; }
        public Nullable<double> FormalTotal { get; set; }
        public Nullable<double> TotalProgress { get; set; }
        public Nullable<double> PrePaymentAmount { get; set; }
        public Nullable<double> SalaryCutAmount { get; set; }
        public Nullable<double> BankPaymentAmount { get; set; }
        public Nullable<double> ManuelPaymentAmount { get; set; }
        public Nullable<double> OtherPaymentAmount { get; set; }
        public Nullable<double> TotalPaymentAmount { get; set; }
        public Nullable<double> TotalBalance { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public string RecordIP { get; set; }
        public Nullable<System.Guid> UID { get; set; }
    }
}
