//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetcardParameter
    {
        public int ID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> EarnHour { get; set; }
        public Nullable<int> TotalHour { get; set; }
        public Nullable<double> UnitAmount { get; set; }
    }
}
