//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSNumber
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsHR { get; set; }
        public Nullable<bool> IsInfo { get; set; }
    }
}
