//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> CriticalLevel { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
    }
}
