//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempDocumentBankTransfer
    {
        public System.Guid UID { get; set; }
        public int StatusID { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string Message { get; set; }
    }
}
