//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempEmployeeActionReset
    {
        public int ID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<int> ActionTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<int> SalaryTypeID { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string Message { get; set; }
    }
}
