//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSalePosReceipt
    {
        public long ID { get; set; }
        public Nullable<long> SaleID { get; set; }
        public Nullable<short> ReceiptNo { get; set; }
        public Nullable<short> ZNo { get; set; }
        public Nullable<short> EkuNo { get; set; }
        public string TransDateTime { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<System.TimeSpan> ReceiptTime { get; set; }
        public Nullable<int> TicketType { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    }
}
