//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketPrice
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> PriceCatID { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> ExtraMultiple { get; set; }
        public string Money { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<bool> AllowPrepaid { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
