//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketPromotionCalender
    {
        public int ID { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> HourBegin { get; set; }
        public Nullable<System.TimeSpan> HourEnd { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
