//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSaleLines
    {
        public long ID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SortBy { get; set; }
        public Nullable<int> State { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
    }
}
