//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public long ID { get; set; }
        public int LocationID { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> EnvironmentID { get; set; }
        public string Prefix { get; set; }
        public int OurCompanyID { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public string TicketNumber { get; set; }
        public string TicketNumberMasked { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public Nullable<System.DateTime> DateSold { get; set; }
        public Nullable<System.DateTime> DateUsed { get; set; }
        public Nullable<System.DateTime> DateCanceled { get; set; }
        public Nullable<System.DateTime> DateStatusChanged { get; set; }
        public Nullable<System.DateTime> DateRefunded { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public bool IsBlocked { get; set; }
        public int Status { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public string LocationIDCode { get; set; }
    }
}
