//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSalePosDiscount
    {
        public long ID { get; set; }
        public Nullable<long> SaleID { get; set; }
        public Nullable<int> IndexOffItem { get; set; }
        public string DiscountText { get; set; }
        public Nullable<int> DiscountType { get; set; }
        public Nullable<int> DiscountValue { get; set; }
        public Nullable<int> Orjin { get; set; }
    }
}
