//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketBasket
    {
        public long ID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> PriceCategoryID { get; set; }
        public int PriceID { get; set; }
        public Nullable<int> TicketProductID { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
        public string Name { get; set; }
        public string TicketNumber { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsSale { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Unit { get; set; }
        public double Price { get; set; }
        public double Total { get; set; }
        public string Money { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public Nullable<bool> IsPromotion { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string Description { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> SaleTypeID { get; set; }
        public Nullable<double> PrePaid { get; set; }
        public Nullable<int> PrePaidCampaignID { get; set; }
    }
}
