//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSaleRows
    {
        public long ID { get; set; }
        public int SaleID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<long> TicketTripID { get; set; }
        public Nullable<int> PaymethodID { get; set; }
        public Nullable<bool> UseImmediately { get; set; }
        public Nullable<int> PriceCategoryID { get; set; }
        public int TicketTypeID { get; set; }
        public string TicketNumber { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> ExtraUnit { get; set; }
        public int PriceID { get; set; }
        public double Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> PrePaid { get; set; }
        public Nullable<double> Total { get; set; }
        public string Currency { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public Nullable<bool> IsPromotion { get; set; }
        public Nullable<bool> IsExchangable { get; set; }
        public string DeviceID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerData { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsSale { get; set; }
    }
}
