//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketConfirm
    {
        public int ID { get; set; }
        public string ConfirmNumber { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> PriceCatID { get; set; }
        public Nullable<int> PaymethodID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> GrossTotal { get; set; }
        public Nullable<double> DiscountTotal { get; set; }
        public Nullable<double> NetTotal { get; set; }
        public Nullable<double> PrepaidTotal { get; set; }
        public string Money { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> PrepaidCampaignID { get; set; }
        public Nullable<int> SaleTypeID { get; set; }
    }
}
