//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTripConfirm
    {
        public long ID { get; set; }
        public string ConfirmNumber { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<int> UnitDuration { get; set; }
        public Nullable<int> AnimalID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> PartID { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Message { get; set; }
    }
}
