//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSaleTransfer
    {
        public int ID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> RowID { get; set; }
        public string TicketNumberOUT { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SaleIDIN { get; set; }
        public Nullable<int> RowIDIN { get; set; }
        public Nullable<System.DateTime> DateIN { get; set; }
        public string TicketNumberIN { get; set; }
        public string LocationMessage { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
