//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketPromotion
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> DatePublish { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> MainPriceID { get; set; }
        public Nullable<int> MainQuantity { get; set; }
        public Nullable<int> PromPriceID { get; set; }
        public Nullable<int> PromQuantity { get; set; }
        public Nullable<int> PromExtraUnit { get; set; }
        public Nullable<double> PromDiscount { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
    }
}
