//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSaleRows
    {
        public int ID { get; set; }
        public int SaleID { get; set; }
        public Nullable<int> ActionRowID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<long> TicketTripID { get; set; }
        public bool IsSale { get; set; }
        public Nullable<bool> IsCash { get; set; }
        public Nullable<int> PaymethodID { get; set; }
        public Nullable<bool> UseImmediately { get; set; }
        public Nullable<bool> IsExtended { get; set; }
        public int TicketTypeID { get; set; }
        public string TicketNumber { get; set; }
        public string PrepaidTicketNumber { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> ExtraUnit { get; set; }
        public Nullable<int> PriceCategoryID { get; set; }
        public int PriceID { get; set; }
        public double Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> PrePaid { get; set; }
        public string Money { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public Nullable<bool> IsPromotion { get; set; }
        public Nullable<bool> IsOpen { get; set; }
        public Nullable<bool> IsExchangable { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string DeviceID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerData { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReferenceOrderID { get; set; }
        public Nullable<int> ReferenceOrderRowID { get; set; }
    }
}
