//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSalePosPayment
    {
        public long ID { get; set; }
        public Nullable<long> SaleID { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string PaymentSubType { get; set; }
        public Nullable<int> NumberOfInstallment { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public string PaymentDesc { get; set; }
        public Nullable<int> PaymentCurrency { get; set; }
        public string PaymentInfo { get; set; }
        public string PaymentDateTime { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.TimeSpan> PaymentTime { get; set; }
        public Nullable<short> BankBKMID { get; set; }
        public string BatchNumber { get; set; }
        public string StanNumber { get; set; }
        public string MerchantID { get; set; }
        public string TerminalID { get; set; }
        public string ReferenceNumber { get; set; }
        public string AuthorizationCode { get; set; }
        public string MaskedPan { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string Currency { get; set; }
    }
}
