//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTrip
    {
        public long ID { get; set; }
        public Nullable<long> ConfirmID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<int> AnimalID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> PartID { get; set; }
        public string PartNumber { get; set; }
        public Nullable<System.DateTime> TripDate { get; set; }
        public Nullable<System.DateTime> TripStart { get; set; }
        public Nullable<System.DateTime> TripCancel { get; set; }
        public Nullable<System.DateTime> TripEnd { get; set; }
        public Nullable<System.TimeSpan> TripDuration { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string IdentityCard { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> TripDurationSn { get; set; }
    }
}
