//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrampolinePart
    {
        public int ID { get; set; }
        public Nullable<int> TrampolineID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<short> Number { get; set; }
        public string Code { get; set; }
        public string PartName { get; set; }
        public string Direction { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
