//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VBankAccount
    {
        public int ID { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public string BranchName { get; set; }
        public string AccountName { get; set; }
        public string BranchCode { get; set; }
        public string RoutingNumber { get; set; }
        public string AccountNumber { get; set; }
        public string Currency { get; set; }
        public string IBAN { get; set; }
        public Nullable<bool> IsMaster { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string TypeName { get; set; }
    }
}
