//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCashRecorderMuhasebe
    {
        public long ID { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> SlipDate { get; set; }
        public string SlipDateDate { get; set; }
        public Nullable<double> CashAmount { get; set; }
        public Nullable<double> CreditAmount { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<double> Matrah { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string Currency { get; set; }
        public string BelgeTuru { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public string RecordIP { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployee { get; set; }
        public string UpdateIP { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ActionTypeName { get; set; }
        public Nullable<int> ActionTypeID { get; set; }
        public string SlipPath { get; set; }
        public string SlipFile { get; set; }
        public string SlipNumber { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public string ActionName { get; set; }
        public string RecorderFullName { get; set; }
        public string UpdaterFullName { get; set; }
        public string LocationFullName { get; set; }
        public Nullable<int> EnvironmentID { get; set; }
        public Nullable<long> ResultID { get; set; }
        public Nullable<int> SlipYear { get; set; }
        public Nullable<int> SlipMonth { get; set; }
    }
}
