//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCashBankActions
    {
        public long ID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> CashID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> BankAccountID { get; set; }
        public Nullable<int> PosID { get; set; }
        public string Module { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string ProcessName { get; set; }
        public Nullable<long> ProcessID { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<short> Direction { get; set; }
        public Nullable<double> CashCollection { get; set; }
        public Nullable<double> CashPaymnet { get; set; }
        public Nullable<double> CashAmount { get; set; }
        public Nullable<double> CardCollection { get; set; }
        public Nullable<double> CardPayment { get; set; }
        public Nullable<double> CardAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.Guid> ProcessUID { get; set; }
    }
}
