//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCashRecorders
    {
        public int LocationID { get; set; }
        public int OurCompanyID { get; set; }
        public string LocationFullName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public int ID { get; set; }
    }
}
