//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCity
    {
        public int ID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public string Code { get; set; }
        public string CityName { get; set; }
        public string SortBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string StateName { get; set; }
        public string CountryName { get; set; }
        public string CompanyName { get; set; }
        public string Currency { get; set; }
        public Nullable<int> TimeZone { get; set; }
        public Nullable<int> TimeZoneTo { get; set; }
        public string Culture { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
    }
}
