//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCustomerCard
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<short> CardTypeID { get; set; }
        public Nullable<int> CardStatuLevel { get; set; }
        public Nullable<short> CardStatusID { get; set; }
        public string CardNumber { get; set; }
        public Nullable<double> Credit { get; set; }
        public string Currency { get; set; }
        public Nullable<int> EnvironmentID { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<bool> IsMaster { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FullName { get; set; }
        public string EMail { get; set; }
        public string CountryCode { get; set; }
        public string PhoneCode { get; set; }
        public string PhoneNumber { get; set; }
        public string SMSNumber { get; set; }
        public string CardStatusName { get; set; }
        public string CardTypeName { get; set; }
        public Nullable<long> CardID { get; set; }
    }
}
