//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDayResultItemList
    {
        public long ID { get; set; }
        public Nullable<long> ResultID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Category { get; set; }
        public Nullable<int> ResultItemID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> SystemQuantity { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> SystemAmount { get; set; }
        public Nullable<double> Exchange { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<double> UnitHourPrice { get; set; }
        public Nullable<double> HourQuantity { get; set; }
        public Nullable<double> SystemHourQuantity { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<int> BankAccountID { get; set; }
        public string SlipNumber { get; set; }
        public Nullable<System.DateTime> SlipDate { get; set; }
        public Nullable<double> SlipTotalAmount { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public string RecordIP { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployee { get; set; }
        public string UpdateIP { get; set; }
        public string ItemCategory { get; set; }
        public string ItemName { get; set; }
        public string AccountName { get; set; }
        public string BranchName { get; set; }
        public string FullName { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public Nullable<System.TimeSpan> SystemDuration { get; set; }
    }
}
