//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDocumentEmployeePermit
    {
        public long ID { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> PermitTypeID { get; set; }
        public Nullable<bool> IsPaidTo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> MinuteDuration { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> QuantityHour { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public Nullable<long> ReferenceID { get; set; }
        public string ActionTypeName { get; set; }
        public Nullable<int> ActionTypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string RecordIP { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateIP { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> ResultID { get; set; }
        public Nullable<int> EnvironmentID { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public string EmployeeFullName { get; set; }
        public string RecorderEmployeeFullName { get; set; }
        public string SortBy { get; set; }
        public string LocationName { get; set; }
        public string Expr1 { get; set; }
        public string State { get; set; }
        public string StatusName { get; set; }
        public string TypeCode { get; set; }
        public string PermitTypeName { get; set; }
        public Nullable<System.DateTime> ReturnWorkDate { get; set; }
    }
}
