//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDocumentPartnerEarnRow
    {
        public long ID { get; set; }
        public Nullable<long> DocumentID { get; set; }
        public Nullable<short> ExpenseGroupID { get; set; }
        public Nullable<double> BaseAmount { get; set; }
        public Nullable<double> PartnerRate { get; set; }
        public Nullable<double> CapacityRate { get; set; }
        public Nullable<double> EarnedAmount { get; set; }
        public Nullable<double> PayedAmount { get; set; }
        public Nullable<double> BalanceAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ExpenseGroupName { get; set; }
    }
}
