//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmpShift
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> ShiftDate { get; set; }
        public Nullable<System.TimeSpan> ShiftStart { get; set; }
        public Nullable<System.TimeSpan> ShiftEnd { get; set; }
        public string Duration { get; set; }
        public Nullable<bool> IsWorkTime { get; set; }
        public Nullable<bool> IsBreakTime { get; set; }
        public Nullable<System.DateTime> ShiftDateStart { get; set; }
        public Nullable<System.DateTime> ShiftDateEnd { get; set; }
        public Nullable<System.TimeSpan> ShiftDuration { get; set; }
        public Nullable<int> DurationMinute { get; set; }
        public string SortBy { get; set; }
        public string LocationName { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
    }
}
