//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmployeeLocationPosition
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<bool> IsMaster { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string EmployeeFullName { get; set; }
        public string LocationFullName { get; set; }
        public string PositionName { get; set; }
    }
}
