//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmployeeModel
    {
        public int EmployeeID { get; set; }
        public string IdentityNumber { get; set; }
        public string FullName { get; set; }
        public string IBAN { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public string BankBranchCode { get; set; }
        public string FoodCardNumber { get; set; }
        public string MobilePhone { get; set; }
        public int OurCompanyID { get; set; }
        public string Currency { get; set; }
        public int AreaCategoryID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> StatusID { get; set; }
    }
}
