//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmployeeLocation
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int LocationID { get; set; }
        public string IdentityNumber { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public string FullNameSearch { get; set; }
        public string EMail { get; set; }
        public string Mobile { get; set; }
        public string Mobile2 { get; set; }
        public string Whatsapp { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FotoFile { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> Stage { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> RoleLevel { get; set; }
        public Nullable<bool> IsMaster { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsTemp { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LocalDate { get; set; }
        public Nullable<System.DateTime> LocalDateTime { get; set; }
        public Nullable<System.DateTime> ShiftDate { get; set; }
        public Nullable<System.DateTime> ShiftDateStart { get; set; }
        public Nullable<System.DateTime> ShiftDateEnd { get; set; }
        public Nullable<System.TimeSpan> ShiftDuration { get; set; }
        public Nullable<System.TimeSpan> BreakStart { get; set; }
        public Nullable<System.TimeSpan> BreakEnd { get; set; }
        public Nullable<System.TimeSpan> BreakDuration { get; set; }
        public Nullable<int> Status { get; set; }
        public int BreakStatus { get; set; }
        public string LocationCode { get; set; }
        public Nullable<int> LocationTypeID { get; set; }
        public string LocationTypeName { get; set; }
        public string LocationName { get; set; }
        public string LocationNameSearch { get; set; }
        public string LocationDescription { get; set; }
        public string State { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> Timezone { get; set; }
        public Nullable<bool> LocationIsActive { get; set; }
        public string SortBy { get; set; }
        public string EnforcedWarning { get; set; }
        public string Currency { get; set; }
        public Nullable<int> PriceCatID { get; set; }
        public string Weight { get; set; }
        public string Distance { get; set; }
        public Nullable<System.DateTime> DateKey { get; set; }
        public Nullable<int> LocationStatus { get; set; }
        public Nullable<bool> IsDismissal { get; set; }
        public Nullable<System.Guid> EmployeeUID { get; set; }
        public Nullable<System.Guid> LocationUID { get; set; }
        public Nullable<int> ERoleStage { get; set; }
        public string ERoleName { get; set; }
        public Nullable<int> ERoleLevel { get; set; }
    }
}
