//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmployeeCashActions
    {
        public int ID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ActionTypeID { get; set; }
        public string ProcessName { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string ProcessDetail { get; set; }
        public Nullable<short> Direction { get; set; }
        public Nullable<double> Collection { get; set; }
        public Nullable<double> Payment { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> SalaryTypeID { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string FullName { get; set; }
        public string Name { get; set; }
        public string RecorderFullName { get; set; }
        public Nullable<int> FromCashID { get; set; }
        public Nullable<int> SalaryType { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> QuantityHour { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string DocumentNumber { get; set; }
        public string DocumentNumberE { get; set; }
        public string SalaryTypeName { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> FromBankAccountID { get; set; }
        public string FromName { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public Nullable<System.Guid> ProcessUID { get; set; }
        public string ActionDocumentNumber { get; set; }
        public Nullable<double> QuantityHourSalary { get; set; }
        public Nullable<double> TotalAmountSalary { get; set; }
        public Nullable<double> QuantityHourFood { get; set; }
        public Nullable<double> UnitFoodPrice { get; set; }
        public Nullable<double> TotalAmountFood { get; set; }
        public Nullable<double> SystemUnitPrice { get; set; }
        public string IBAN { get; set; }
        public string BankName { get; set; }
        public string IdentityNumber { get; set; }
        public string BankCode { get; set; }
        public string BankBranchCode { get; set; }
        public string FoodCardNumber { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
    }
}
