//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmployeePhones
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> PhoneTypeID { get; set; }
        public string Description { get; set; }
        public string CountryPhoneCode { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> IsMaster { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PhoneTypeName { get; set; }
    }
}
