//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmployee
    {
        public int EmployeeID { get; set; }
        public string IdentityNumber { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public string FullNameSearch { get; set; }
        public string EMail { get; set; }
        public string Mobile { get; set; }
        public string Mobile2 { get; set; }
        public string Whatsapp { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FotoFile { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> Stage { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> RoleLevel { get; set; }
        public int OurCompanyID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsTemp { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDismissal { get; set; }
        public Nullable<int> ShiftTypeID { get; set; }
        public string CompanyName { get; set; }
        public string Code { get; set; }
        public string DismissDescription { get; set; }
        public Nullable<int> RoleGroupID { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.Guid> EmployeeUID { get; set; }
        public string IBAN { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<short> SalaryPaymentTypeID { get; set; }
    }
}
