//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmployeeAll
    {
        public int EmployeeID { get; set; }
        public string IdentityType { get; set; }
        public string IdentityNumber { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public string FullNameSearch { get; set; }
        public string EMail { get; set; }
        public string CountryPhoneCode { get; set; }
        public string Mobile { get; set; }
        public string FotoFile { get; set; }
        public Nullable<int> RoleID { get; set; }
        public int OurCompanyID { get; set; }
        public string OurCompanyName { get; set; }
        public string OurCompanyCode { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDismissal { get; set; }
        public string DismissDescription { get; set; }
        public string Mobile2 { get; set; }
        public string Whatsapp { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.Guid> EmployeeUID { get; set; }
        public Nullable<int> ShiftTypeID { get; set; }
        public string ShiftTypeName { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string StatusCode { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> RoleGroupID { get; set; }
        public Nullable<int> RoleLevel { get; set; }
        public string RoleGroupCode { get; set; }
        public string RoleGroupName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> AreaCategoryID { get; set; }
        public string WorkAreaName { get; set; }
        public Nullable<int> SalaryCategoryID { get; set; }
        public string SalaryCategoryName { get; set; }
        public Nullable<int> SequenceID { get; set; }
        public string SequenceCode { get; set; }
        public string SequenceName { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string PositionName { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string RecordEmployeeName { get; set; }
        public string RecordIP { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateEmployeeName { get; set; }
        public string UpdateIP { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
