//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmployeeLocationList
    {
        public int ID { get; set; }
        public int OurCompanyID { get; set; }
        public int EmployeeID { get; set; }
        public int LocationID { get; set; }
        public string FullName { get; set; }
        public string RoleName { get; set; }
        public string LocationName { get; set; }
        public string TypeName { get; set; }
        public string State { get; set; }
        public string Description { get; set; }
    }
}
