//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmployeeAddress
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> AddressTypeID { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> City { get; set; }
        public string PostCode { get; set; }
        public Nullable<bool> IsMaster { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string AddressTypeName { get; set; }
        public string CityName { get; set; }
        public string StateName { get; set; }
        public string CountryName { get; set; }
    }
}
