//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmployeeSalary
    {
        public int EmployeeID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<double> Hourly { get; set; }
        public string Money { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<double> HourlyExtend { get; set; }
        public Nullable<double> ExtendMultiplyRate { get; set; }
    }
}
