//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VExpenseDocument
    {
        public long ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> ExpenseCenterID { get; set; }
        public Nullable<short> ExpenseGroupID { get; set; }
        public string ExpensePeriodCode { get; set; }
        public Nullable<short> ExpenseItemID { get; set; }
        public string DocumentNumber { get; set; }
        public string DocumentSource { get; set; }
        public string ExpenseDescription { get; set; }
        public Nullable<System.DateTime> ExpensePeriod { get; set; }
        public Nullable<int> ExpenseYear { get; set; }
        public Nullable<int> ExpenseMonth { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> DistributionAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public string RecordIP { get; set; }
        public Nullable<short> StatusID { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string StatusName { get; set; }
        public string ExpenseGroupName { get; set; }
        public string ExpenseItemName { get; set; }
        public string PeriodCode { get; set; }
        public Nullable<int> DateYear { get; set; }
        public string ExpenseCenterName { get; set; }
        public Nullable<short> AutoComputeTypeID { get; set; }
        public Nullable<int> DateMonth { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<double> TaxAmount { get; set; }
    }
}
