//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VExpenseDocumentLocationsVat
    {
        public long ID { get; set; }
        public long ExpenseDocumentID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string ExpensePeriodCode { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<double> DistributedAmount { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public string Currency { get; set; }
    }
}
