//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VExpenseDocumentRows
    {
        public long ID { get; set; }
        public Nullable<long> DocumentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<double> Unit { get; set; }
        public Nullable<double> Hour { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> CostAmount { get; set; }
        public Nullable<double> PremiumAmount { get; set; }
        public Nullable<double> SGKCostAmount { get; set; }
        public Nullable<double> FoodCardCostAmount { get; set; }
        public string Currency { get; set; }
        public string FullName { get; set; }
        public string LocationFullName { get; set; }
    }
}
