//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLocationPriceCategory
    {
        public int ID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> PriceCategoryID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string RecordIP { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public string UpdateIP { get; set; }
        public string CategoryName { get; set; }
        public string REmployeeName { get; set; }
        public string UEmployeeName { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
        public string TicketTypeName { get; set; }
        public string CategoryName1 { get; set; }
        public string CategoryName2 { get; set; }
        public string CategoryName3 { get; set; }
        public string CategoryName4 { get; set; }
        public string CategoryName5 { get; set; }
        public string CategoryName6 { get; set; }
        public string CategoryName7 { get; set; }
        public Nullable<int> MondayPCID { get; set; }
        public Nullable<int> TuesdayPCID { get; set; }
        public Nullable<int> WednesdayPCID { get; set; }
        public Nullable<int> ThursdayPCID { get; set; }
        public Nullable<int> FridayPCID { get; set; }
        public Nullable<int> SaturdayPCID { get; set; }
        public Nullable<int> SundayPCID { get; set; }
    }
}
