//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLocationPartEmployee
    {
        public long ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> LocationTypeID { get; set; }
        public Nullable<int> LocationPartID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<System.DateTime> ReadDay { get; set; }
        public string FullName { get; set; }
        public string PartName { get; set; }
    }
}
