//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLocation
    {
        public int LocationID { get; set; }
        public string LocationCode { get; set; }
        public Nullable<int> LocationTypeID { get; set; }
        public string LocationTypeName { get; set; }
        public string LocationName { get; set; }
        public string LocationNameSearch { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> Timezone { get; set; }
        public string MapURL { get; set; }
        public int OurCompanyID { get; set; }
        public string ImageFile { get; set; }
        public Nullable<bool> IsHaveOperator { get; set; }
        public string IP { get; set; }
        public string EnforcedWarning { get; set; }
        public string SortBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Currency { get; set; }
        public Nullable<int> PriceCatID { get; set; }
        public string Weight { get; set; }
        public string Distance { get; set; }
        public Nullable<System.DateTime> LocalDateTime { get; set; }
        public Nullable<System.DateTime> LocalDate { get; set; }
        public Nullable<int> DateID { get; set; }
        public Nullable<System.DateTime> DateKey { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> DayOfYear { get; set; }
        public string MonthName { get; set; }
        public string DayName { get; set; }
        public string MonthNameTR { get; set; }
        public string DayNameTR { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> WeekYear { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<System.DateTime> ScheduleStart { get; set; }
        public Nullable<System.DateTime> ScheduleEnd { get; set; }
        public Nullable<System.DateTime> ShiftDate { get; set; }
        public Nullable<System.TimeSpan> ShiftStart { get; set; }
        public Nullable<System.TimeSpan> ShiftFinish { get; set; }
        public Nullable<System.DateTime> ShiftDateStart { get; set; }
        public Nullable<System.DateTime> ShiftDateFinish { get; set; }
        public string Duration { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
        public Nullable<System.Guid> LocationUID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> POSAccountID { get; set; }
        public Nullable<int> MallID { get; set; }
        public string LocationFullName { get; set; }
        public string ERName { get; set; }
        public string EUName { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.TimeSpan> ScheduleDuration { get; set; }
        public string WeekKey { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string CityName { get; set; }
        public string CategoryName { get; set; }
        public Nullable<double> TaxRate { get; set; }
    }
}
