//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLocationPosTerminal
    {
        public int LocationID { get; set; }
        public int OurCompanyID { get; set; }
        public string LocationFullName { get; set; }
        public string BrandName { get; set; }
        public string ClientID { get; set; }
        public string ModelName { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> TerminalID { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> BankAccountID { get; set; }
    }
}
