//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLocationSchedule
    {
        public long ID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> ShiftDate { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> Day { get; set; }
        public string DayName { get; set; }
        public Nullable<System.DateTime> ShiftDateStart { get; set; }
        public Nullable<System.DateTime> ShiftdateEnd { get; set; }
        public string ShiftDateStartString { get; set; }
        public string ShiftDateEndString { get; set; }
        public Nullable<int> DurationMinute { get; set; }
        public Nullable<int> RecordEmployee { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string RecordIP { get; set; }
        public Nullable<int> UpdateEmployee { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateIP { get; set; }
        public string LocationFullName { get; set; }
        public string Status { get; set; }
        public string Color { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public string WeekCode { get; set; }
        public Nullable<double> UnitPriceMultiplier { get; set; }
        public string ScheduleKey { get; set; }
        public Nullable<System.TimeSpan> ShiftDuration { get; set; }
    }
}
