//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLocationAnimals
    {
        public int ID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string LocationName { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
        public string SortBy { get; set; }
        public Nullable<int> LocationTypeID { get; set; }
        public Nullable<System.DateTime> LocalDate { get; set; }
        public Nullable<System.DateTime> LocalDateTime { get; set; }
        public int AnimalID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public int ChassisID { get; set; }
        public int CostumeID { get; set; }
        public string Number { get; set; }
        public Nullable<int> ChassisTypeID { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> CostumeTypeID { get; set; }
        public string TypeNameTR { get; set; }
        public string TypeNameEN { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SerialNumber { get; set; }
        public int SerialID { get; set; }
        public string LocationFullName { get; set; }
        public int OurCompanyID { get; set; }
    }
}
