//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPartnership
    {
        public int ID { get; set; }
        public Nullable<int> PartnerID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<double> PartnershipRate { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string AccountCode { get; set; }
        public string FullName { get; set; }
        public string LocationFullName { get; set; }
    }
}
