//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPosTerminal
    {
        public int ID { get; set; }
        public string TerminalID { get; set; }
        public string ClientID { get; set; }
        public Nullable<int> BankAccountID { get; set; }
        public string BrandName { get; set; }
        public string ModelName { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> BankID { get; set; }
        public string BranchName { get; set; }
        public string AccountName { get; set; }
        public string Name { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public string SicilNumber { get; set; }
    }
}
