//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VProductPriceLastList
    {
        public int ID { get; set; }
        public int OurCompanyID { get; set; }
        public int ProductPriceCategoryID { get; set; }
        public int ProductID { get; set; }
        public double Price { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<double> MasterCredit { get; set; }
        public Nullable<double> PromoCredit { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<bool> IsBase { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> CardTypeID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string UnitCode { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string PriceCategoryName { get; set; }
        public Nullable<bool> UseToSale { get; set; }
        public double TotalCredit { get; set; }
        public Nullable<bool> UseToDeposite { get; set; }
    }
}
