//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRevenue
    {
        public long ID { get; set; }
        public Nullable<int> WeekYear { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Currency { get; set; }
        public Nullable<double> TotalCash { get; set; }
        public Nullable<double> TotalCredit { get; set; }
        public Nullable<double> GrossTotal { get; set; }
        public Nullable<double> Net { get; set; }
        public Nullable<double> Operator { get; set; }
        public Nullable<double> ActionTime { get; set; }
        public Nullable<double> OpReturn { get; set; }
        public Nullable<int> ComputedType { get; set; }
        public Nullable<double> ComputedRate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<double> TotalLabor { get; set; }
        public Nullable<double> TotalExpense { get; set; }
        public Nullable<double> TotalCashIn { get; set; }
        public Nullable<double> TotalRent { get; set; }
        public Nullable<double> TotalCreditCommission { get; set; }
        public Nullable<double> TotalInsurance { get; set; }
        public string SortBy { get; set; }
        public string LocationFullName { get; set; }
        public int OurCompanyID { get; set; }
        public Nullable<double> RentMonthly { get; set; }
        public Nullable<double> InsuranceMonthly { get; set; }
    }
}
