//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSalaryPeriod
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<short> SalaryPeriodGroupID { get; set; }
        public Nullable<short> SalaryPeriodStatusID { get; set; }
        public string PeriodCode { get; set; }
        public int Year { get; set; }
        public Nullable<int> Month { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public string Currency { get; set; }
        public string CompanyName { get; set; }
        public string StatusName { get; set; }
        public Nullable<short> GroupType { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> EmployeeAreaCategoryID { get; set; }
        public Nullable<short> DayCount { get; set; }
        public string AreaName { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public Nullable<double> BalanceAmount { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> IsCostCompute { get; set; }
        public Nullable<bool> HaveChild { get; set; }
    }
}
