//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSalaryPeriodComputeSum
    {
        public int SalaryPeriodID { get; set; }
        public Nullable<double> SalaryTotal { get; set; }
        public Nullable<double> PermitTotal { get; set; }
        public Nullable<double> ExtraShiftTotal { get; set; }
        public Nullable<double> PremiumTotal { get; set; }
        public Nullable<double> FormalTotal { get; set; }
        public Nullable<double> OtherTotal { get; set; }
        public Nullable<double> TotalProgress { get; set; }
        public Nullable<double> PrePaymentAmount { get; set; }
        public Nullable<double> SalaryCutAmount { get; set; }
        public Nullable<double> BankPaymentAmount { get; set; }
        public Nullable<double> ManuelPaymentAmount { get; set; }
        public Nullable<double> OtherPaymentAmount { get; set; }
        public Nullable<double> TotalPaymentAmount { get; set; }
        public Nullable<double> TotalBalance { get; set; }
        public string Currency { get; set; }
        public Nullable<double> FoodCardTotal { get; set; }
        public Nullable<double> FoodCardPaymentAmount { get; set; }
        public Nullable<double> PermitPaymentAmount { get; set; }
        public Nullable<double> ExtraShiftPaymentAmount { get; set; }
        public Nullable<double> PremiumPaymentAmount { get; set; }
        public Nullable<double> FormalPaymentAmount { get; set; }
        public Nullable<double> FoodcardBalance { get; set; }
        public Nullable<double> TransferBalance { get; set; }
        public Nullable<double> GrossBalance { get; set; }
        public Nullable<double> SSK { get; set; }
        public Nullable<double> GV { get; set; }
        public Nullable<double> DV { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<double> NetCost { get; set; }
    }
}
