//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSaleActionsSummaryUnion
    {
        public long ID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> ActionTypeID { get; set; }
        public string ProcessName { get; set; }
        public Nullable<long> ProcessID { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.Guid> ProcessUID { get; set; }
    }
}
