//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSchedule
    {
        public long Id { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> ShiftDate { get; set; }
        public string Shift { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> RecordEmployee { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string RecordIP { get; set; }
        public Nullable<int> UpdateEmployee { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateIP { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public Nullable<int> WeekYear { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> DayOfYear { get; set; }
        public string MonthName { get; set; }
        public string DayName { get; set; }
        public string MonthNameTR { get; set; }
        public Nullable<int> Quarter { get; set; }
        public string DayNameTR { get; set; }
        public string FullName { get; set; }
        public string LocationName { get; set; }
        public string LocationTypeName { get; set; }
        public Nullable<bool> LocationIsActive { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> ShiftDateStart { get; set; }
        public Nullable<System.DateTime> ShiftdateEnd { get; set; }
        public Nullable<int> DurationMinute { get; set; }
        public string ShiftDateStartString { get; set; }
        public string ShiftDateEndString { get; set; }
    }
}
