//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSystemCheckEmployeeRows
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CriteriaID { get; set; }
        public Nullable<int> CheckTypeID { get; set; }
        public string Description { get; set; }
        public string Parameter { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> DateKey { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> RecorderID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FullName { get; set; }
        public string LocationName { get; set; }
        public string LocationTypeName { get; set; }
        public string State { get; set; }
        public string TypeName { get; set; }
        public string Recorder { get; set; }
        public string Code { get; set; }
    }
}
