//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTicketSalePaymentSummary
    {
        public long ID { get; set; }
        public Nullable<long> SaleID { get; set; }
        public Nullable<bool> FromPosTerminal { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.TimeSpan> PaymentTime { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> PosStatusID { get; set; }
    }
}
