//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTicketSalePosPaymentSummary
    {
        public Nullable<long> SaleID { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string PaymentTypeName { get; set; }
        public string PaymentSubType { get; set; }
        public string PaymentSubTypeName { get; set; }
        public Nullable<int> NumberOfInstallment { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public string Currency { get; set; }
        public string Sign { get; set; }
    }
}
