//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTicketPromotion
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> DatePublish { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Status { get; set; }
        public Nullable<int> MainPriceID { get; set; }
        public Nullable<int> MainQuantity { get; set; }
        public Nullable<int> PromPriceID { get; set; }
        public Nullable<int> PromQuantity { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public Nullable<int> PromExtraUnit { get; set; }
        public Nullable<double> PromDiscount { get; set; }
        public Nullable<int> PriceCategoryID { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<double> Price { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> UseToSale { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Unit { get; set; }
        public string ProductCategoryName { get; set; }
        public string TicketTypeName { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> IsMaster { get; set; }
        public string CompanyName { get; set; }
        public string Style { get; set; }
        public string Sign { get; set; }
        public string BackStyle { get; set; }
        public string ProductDescription { get; set; }
    }
}
