//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTicketProduct
    {
        public int ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public string RecordIP { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public string UpdateIP { get; set; }
        public string CompanyName { get; set; }
        public string ProductName { get; set; }
        public string ProductCategoryName { get; set; }
        public string TicketTypeName { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<double> Tax { get; set; }
    }
}
