//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTicketSaleRowSummary
    {
        public long ID { get; set; }
        public long SaleID { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public Nullable<double> RowTotal { get; set; }
        public string Currency { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string StatusName { get; set; }
        public string StatusColor { get; set; }
        public Nullable<int> SaleRowUnit { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public string Sign { get; set; }
        public string ProductName { get; set; }
    }
}
