//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTicketSaleCreditLoad
    {
        public long ID { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> CardActionTypeID { get; set; }
        public Nullable<long> SaleID { get; set; }
        public Nullable<bool> FromCardReader { get; set; }
        public Nullable<long> CardReaderActionID { get; set; }
        public Nullable<long> CardActionID { get; set; }
        public Nullable<bool> WithCard { get; set; }
        public Nullable<short> CardTypeID { get; set; }
        public string CardNumber { get; set; }
        public double ExistsCredit { get; set; }
        public double MasterCredit { get; set; }
        public double PromoCredit { get; set; }
        public double RefundCredit { get; set; }
        public double TotalCredit { get; set; }
        public Nullable<double> FinalCredit { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string SerialNumber { get; set; }
        public string MACAddress { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public string RecordIP { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
        public string CardActionTypeName { get; set; }
        public string CardTypeName { get; set; }
        public string Sign { get; set; }
    }
}
