//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTicketSaleAllSummary
    {
        public long ID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> PosStatusID { get; set; }
        public Nullable<int> EnvironmentID { get; set; }
        public System.Guid UID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public double Total { get; set; }
        public string Currency { get; set; }
        public string Sign { get; set; }
        public string FullName { get; set; }
        public double PaymentAmount { get; set; }
        public double BalanceAmount { get; set; }
        public string PosStatusName { get; set; }
        public Nullable<bool> IsSendPosTerminal { get; set; }
        public string PayMethodList { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Environment { get; set; }
        public string SortBy { get; set; }
        public string LocationFullName { get; set; }
        public string Name { get; set; }
    }
}
