//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTicketSale
    {
        public int ID { get; set; }
        public string OrderNumber { get; set; }
        public string SaleDetail { get; set; }
        public Nullable<int> ActionRowID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerData { get; set; }
        public string CustomerPhone { get; set; }
        public string IdentityCard { get; set; }
        public Nullable<int> SaleChannelD { get; set; }
        public Nullable<int> PriceCategoryID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Description { get; set; }
        public string LocationName { get; set; }
        public string LocationDescription { get; set; }
        public string State { get; set; }
        public string CatName { get; set; }
        public string SalerFullName { get; set; }
        public string RecorderFullName { get; set; }
        public int OurCompanyID { get; set; }
        public Nullable<int> PaymethodID { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<double> SaleCash { get; set; }
        public Nullable<double> SaleCredit { get; set; }
        public string Money { get; set; }
        public string MethodName { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> SaleTotal { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SaleTypeID { get; set; }
        public string SaleTypeName { get; set; }
        public Nullable<double> SalePrePaidTotal { get; set; }
        public Nullable<int> PrepaidCampaignID { get; set; }
        public string CampaignName { get; set; }
    }
}
