//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTicketSaleRowCheck
    {
        public long ID { get; set; }
        public long OrderID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public int Status { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public string LocationIDCode { get; set; }
        public bool IsBlocked { get; set; }
        public string TicketNumber { get; set; }
        public int LocationID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string StatusName { get; set; }
        public string TicketNumberMasked { get; set; }
        public string LocationFullName { get; set; }
        public int TicketTypeID { get; set; }
        public string TicketTypeName { get; set; }
        public string Currency { get; set; }
    }
}
