//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTicketSaleRowsAll
    {
        public long ID { get; set; }
        public long OrderID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string SaleCustomerName { get; set; }
        public string SaleCustomerData { get; set; }
        public string SaleCustomerPhone { get; set; }
        public string SaleIdentityCard { get; set; }
        public Nullable<int> SaleChannelD { get; set; }
        public Nullable<int> PriceCategoryID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> RecordEmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string SaleDescription { get; set; }
        public string LocationName { get; set; }
        public string LocationDescription { get; set; }
        public string State { get; set; }
        public string SalerFullName { get; set; }
        public string RecorderFullName { get; set; }
        public Nullable<int> OurCompanyID { get; set; }
        public Nullable<int> SalePaymethodID { get; set; }
        public string SaleCurrency { get; set; }
        public string MethodName { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int TicketTypeID { get; set; }
        public string TicketNumber { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public int PriceID { get; set; }
        public double Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> RowTotal { get; set; }
        public string Currency { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public Nullable<bool> IsPromotion { get; set; }
        public Nullable<bool> IsExchangable { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string DeviceID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> UpdateEmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerData { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public Nullable<int> PriceUnit { get; set; }
        public Nullable<double> TicketPrice { get; set; }
        public string TicketMoney { get; set; }
        public string TicketTypeName { get; set; }
        public string TicketNumberMasked { get; set; }
        public string StatusName { get; set; }
        public string StatusColor { get; set; }
        public Nullable<int> SaleTypeID { get; set; }
        public Nullable<double> PrePaid { get; set; }
        public string TicketSaleTypeName { get; set; }
        public Nullable<long> TicketTripID { get; set; }
        public string PriceCurrency { get; set; }
        public string PriceCategoryName { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<double> SaleAmount { get; set; }
        public Nullable<int> SaleRowUnit { get; set; }
        public Nullable<bool> IsFinancialization { get; set; }
        public Nullable<int> PosStatusID { get; set; }
        public Nullable<int> EnvironmentID { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<double> TaxAmount { get; set; }
    }
}
