//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionForce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekList
    {
        public long Id { get; set; }
        public string WeekCode { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Week { get; set; }
    }
}
